openapi: 3.1.0
info:
  title: Get Points Ledger Information in Connected Orgs
  version: '1.0'
servers:
- url: https://{host}
  variables:
    host:
      default: host
security:
- sec0: []
paths:
  /v2.1/pointsLedger/getCustomerLedgerInfo:
    get:
      summary: Get Points Ledger Information in Connected Orgs
      description: ''
      operationId: connectedorgs-get-customer-ledger-info
      parameters:
      - name: identifierName
        in: query
        description: 'Identifier type to identify the customer or group. For user groups, the following
          identifiers are applicable: groupId, externalId, and primaryUserId. For customers, the applicable
          identifiers include mobile, email, externalId, cuid, and id.'
        required: true
        schema:
          type: string
      - name: identifierValue
        in: query
        description: Value of the specified identifier type of the customer.
        required: true
        schema:
          type: string
      - name: source
        in: query
        description: Source in which the identifier is available.
        required: true
        schema:
          type: string
      - name: accountId
        in: query
        description: For a source with multiple accounts, pass the specific accountId in which the customer
          identifier is available.
        schema:
          type: string
      - name: tillId
        in: query
        description: Get the customer’s ledger information of a specific TILL. Pass the unique till ID.
        schema:
          type: integer
          format: int32
          default: 10
      - name: limit
        in: query
        description: Number of results to retrieve. Max value supported is 10.
        schema:
          type: integer
          format: int32
      - name: offset
        in: query
        description: Page number to show.
        schema:
          type: integer
          format: int32
          default: 0
      - name: programId
        in: query
        description: Retrieve the ledger details of a specific program. By default, details of all programs
          will be retrieved.
        schema:
          type: integer
          format: int32
      - name: startDate
        in: query
        description: Get ledger information from on or after a specific date. Pass the start date in YYYY-MM-DDThh:mm:ss
          format. Default value is 90 days
        schema:
          type: string
      - name: endDate
        in: query
        description: Get ledger information until a specific date. Pass the end date in YYYY-MM-DDThh:mm:ss
          format. Default value is 90 days
        schema:
          type: string
      - name: includeTillConceptEvents
        in: query
        description: Pass true to fetch deduction entries that were triggered at the tills mapped to the
          Concept of the Program ID even if the deductions are from a different program. Default value
          is false. When true, pass the programId also, else it will be qualified as invalid input combination.
        schema:
          type: boolean
      - name: ledgerEntryType
        in: query
        description: The type of ledger entries to fetch. By default, it fetches all the ledger entry
          types.
        schema:
          type: string
      - name: pointCategoryType
        in: query
        description: The point category type for which you want to fetch ledger details. By default, it
          fetches all the points category details.
        schema:
          type: string
      - name: type
        in: query
        description: Setting this field returns entries for type of user, whether individual customer
          or a group. Only two values are allowed here - CUTSOMER, USERGROUP2
        schema:
          type: string
      - name: isPrimaryUser
        in: query
        description: Returns entry for the primary member of a group, in case of usergroups.
        schema:
          type: boolean
      - name: excludeEvents
        in: query
        description: Exclude certain events if you dont want to retrieve entries from that event.
        schema:
          type: string
      - name: eventFilter
        in: query
        description: Retrieves the value of that particular event, which is passed in this filed. Eg.
          TransactionAdd, CustomerRegistration etc.
        schema:
          type: string
      - name: roles
        in: query
        description: These are the roles defined by the brands for members in a user group. For example,
          PRIMARY, SECONDARY, and so on.
        schema:
          type: string
      - name: includeLastOneYearData
        in: query
        description: If set to true, the API response will include data from the last year instead of
          the last 90 days when only startDate or endDate is passed in the API query parameter.
        schema:
          type: boolean
      - name: order
        in: query
        description: Sort the order of entries from date. ASC or DESC
        schema:
          type: string
      - name: isFilterBasedOnDate
        in: query
        description: Indicates whether the date filter should be applied when fetching data from the database.
        schema:
          type: boolean
      - name: includeAlternateCurrencies
        in: query
        description: Pass includeAlternateCurrencies=true to retrieve all alternate currencies available
          with the customer.
        schema:
          type: boolean
      - name: alternateCurrencyNames
        in: query
        description: Filter alternate currencies for the customer based on the name. You can also pass
          a list of comma-separated alternate currency names. Set the parameter includeAlternateCurrencies
          to false when you use this. If the value is true, includeAlternateCurrencies lists all the available
          currencies.
        schema:
          type: string
      - name: DATA-SCOPE-ORG
        in: header
        description: List of Organization IDs
        schema:
          type: string
      - name: DATA-SCOPE
        in: header
        description: The scope to authorize access (SELF, OTHER, ALL)
        required: true
        schema:
          type: string
      responses:
        '200':
          description: '200'
          content:
            application/json:
              examples:
                CUSTOMER:
                  value:
                    customerDetails:
                      firstName: Sushant
                      lastName: Raj
                      userId: 347297848
                      entityType: CUSTOMER
                    ledgerDetails:
                      pageNumber: 0
                      pageSize: 10
                      totalEntries: 2
                      pageCount: 1
                      ledgerClosingBalance: []
                    ledgerEntries:
                    - eventLogId: 13499091
                      eventName: TransactionAdd
                      customerId: 347297848
                      ledgerCreatedDate: Fri Aug 30 11:17:57 GMT 2024
                      customerDetails:
                        userId: 0
                      entryDetails:
                      - ledgerEntryType: CREDIT
                        points: '100.000'
                        pointsCategory: Main
                        programName: ChildOrg1DefaultProgram
                        programId: 1148
                      netPointsOnEvent: '100.000'
                      transactionDetails:
                        transactionId: 36363905
                        transactionNumber: '1725016677'
                        date: '2024-08-30 11:17:57.0'
                        amount: 5000.0
                        grossBillAmount: 5000.0
                        source: instore
                      store: Store1
                      storeCode: store1
                      tillCode: childorgtill1
                      eventDetails: {}
                      sourceProgramId: 1148
                      sourceProgramName: ChildOrg1DefaultProgram
                      orgId: 50406
                    - eventLogId: 13499017
                      eventName: CustomerRegistration
                      customerId: 347297848
                      ledgerCreatedDate: Fri Aug 30 11:09:02 GMT 2024
                      customerDetails: null
                      entryDetails:
                      - ledgerEntryType: OPENING_BALANCE
                        points: '0.000'
                        pointsCategory: DelayedAccrualPointCategory
                        programName: ChildOrg1DefaultProgram
                        programId: 1148
                      - ledgerEntryType: OPENING_BALANCE
                        points: '0.000'
                        pointsCategory: ExternalTriggerBasedPointCategory
                        programName: ChildOrg1DefaultProgram
                        programId: 1148
                      - ledgerEntryType: OPENING_BALANCE
                        points: '0.000'
                        pointsCategory: Main
                        programName: ChildOrg1DefaultProgram
                        programId: 1148
                      netPointsOnEvent: '0.000'
                      transactionDetails: {}
                      store: Store1
                      storeCode: store1
                      tillCode: childorgtill1
                      eventDetails: {}
                      sourceProgramId: 1148
                      sourceProgramName: ChildOrg1DefaultProgram
                      orgId: 50406
                    warnings: []
                GROUP:
                  value:
                    ledgerDetails:
                      pageNumber: 0
                      pageSize: 10
                      totalEntries: 2
                      pageCount: 1
                    ledgerEntries:
                    - eventLogId: 508308379
                      eventName: AllocateGoodwillPoints
                      customerId: -2860
                      ledgerCreatedDate: '2023-06-21 13:34:16.0'
                      customerDetails: null
                      entryDetails:
                      - ledgerEntryType: CREDIT
                        points: '350.000'
                        pointsCategory: Main
                        programName: Default Program
                        programId: 469
                      netPointsOnEvent: '350.000'
                      transactionDetails: {}
                      store: test
                      storeCode: teststore
                      tillCode: neestoretillssnee23
                      eventDetails:
                        reason: POINTS_ISSUE
                    - eventLogId: 508308319
                      eventName: AllocateGoodwillPoints
                      customerId: -2860
                      ledgerCreatedDate: '2023-06-21 13:32:44.0'
                      customerDetails: null
                      entryDetails:
                      - ledgerEntryType: CREDIT
                        points: '100.000'
                        pointsCategory: Main
                        programName: Default Program
                        programId: 469
                      netPointsOnEvent: '100.000'
                      transactionDetails: {}
                      store: test
                      storeCode: teststore
                      tillCode: neestoretillssnee23
                      eventDetails:
                        reason: POINTS_ISSUE
                        sourceProgramId: 1148
                        sourceProgramName: ChildOrg1DefaultProgram
                        orgId: 50406
                    warnings: []
              schema:
                type: object
                properties:
                  customerDetails:
                    type: object
                    properties:
                      firstName:
                        type: string
                        example: Sushant
                      lastName:
                        type: string
                        example: Raj
                      userId:
                        type: integer
                        example: 347297848
                        default: 0
                      entityType:
                        type: string
                        example: CUSTOMER
                  ledgerDetails:
                    type: object
                    properties:
                      pageNumber:
                        type: integer
                        example: 0
                        default: 0
                      pageSize:
                        type: integer
                        example: 10
                        default: 0
                      totalEntries:
                        type: integer
                        example: 2
                        default: 0
                      pageCount:
                        type: integer
                        example: 1
                        default: 0
                      ledgerClosingBalance:
                        type: array
                  ledgerEntries:
                    type: array
                    items:
                      type: object
                      properties:
                        eventLogId:
                          type: integer
                          example: 13499091
                          default: 0
                        eventName:
                          type: string
                          example: TransactionAdd
                        customerId:
                          type: integer
                          example: 347297848
                          default: 0
                        ledgerCreatedDate:
                          type: string
                          example: Fri Aug 30 11:17:57 GMT 2024
                        customerDetails:
                          type: object
                          properties:
                            userId:
                              type: integer
                              example: 0
                              default: 0
                        entryDetails:
                          type: array
                          items:
                            type: object
                            properties:
                              ledgerEntryType:
                                type: string
                                example: CREDIT
                              points:
                                type: string
                                example: '100.000'
                              pointsCategory:
                                type: string
                                example: Main
                              programName:
                                type: string
                                example: ChildOrg1DefaultProgram
                              programId:
                                type: integer
                                example: 1148
                                default: 0
                        netPointsOnEvent:
                          type: string
                          example: '100.000'
                        transactionDetails:
                          type: object
                          properties:
                            transactionId:
                              type: integer
                              example: 36363905
                              default: 0
                            transactionNumber:
                              type: string
                              example: '1725016677'
                            date:
                              type: string
                              example: '2024-08-30 11:17:57.0'
                            amount:
                              type: integer
                              example: 5000
                              default: 0
                            grossBillAmount:
                              type: integer
                              example: 5000
                              default: 0
                            source:
                              type: string
                              example: instore
                        store:
                          type: string
                          example: Store1
                        storeCode:
                          type: string
                          example: store1
                        tillCode:
                          type: string
                          example: childorgtill1
                        eventDetails:
                          type: object
                          properties: {}
                        sourceProgramId:
                          type: integer
                          example: 1148
                          default: 0
                        sourceProgramName:
                          type: string
                          example: ChildOrg1DefaultProgram
                        orgId:
                          type: integer
                          example: 50406
                          default: 0
                  warnings:
                    type: array
        '400':
          description: '400'
          content:
            application/json:
              examples:
                Result:
                  value:
                    errors:
                    - status: false
                      code: 8003
                      message: Invalid source
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        status:
                          type: boolean
                          example: false
                          default: true
                        code:
                          type: integer
                          example: 8003
                          default: 0
                        message:
                          type: string
                          example: Invalid source
      deprecated: false
      x-readme:
        code-samples:
        - language: curl
          code: |-
            curl --location 'https://host/v2.1/pointsLedger/getCustomerLedgerInfo?identifierName=mobile&identifierValue=9988221100&source=INSTORE' \
            --header 'DATA-SCOPE: OTHER' \
            --header 'DATA-SCOPE-ORG: 50405' \
        samples-languages:
        - curl
components:
  securitySchemes:
    sec0:
      type: http
      scheme: basic
