openapi: 3.1.0
info:
  title: Get badges for customer
  version: '1.0'
servers:
- url: https://{host}
  variables:
    host:
      default: host
security:
- sec0: []
paths:
  /api_gateway/v1/badges/customer/{customerId}:
    get:
      summary: Get badges for customer
      description: ''
      operationId: get-badges-for-customer
      parameters:
      - name: badgeType
        in: query
        description: The type of badge to display
        schema:
          type: string
          enum:
          - AVAILABLE
          - EARNED
          default: AVAILABLE
      - name: includeExpired
        in: query
        description: This is the earn expiry. If true then all the earned badges which are even expired
          will be part of the response. If false, then only the badges where earn is active will be a
          part of the response
        schema:
          type: boolean
      - name: customerId
        in: path
        schema:
          type: string
        required: true
      - name: sortOn
        in: query
        description: 'Enables sorting of badges based on rank. Value: rank.'
        schema:
          type: string
      - name: X-CAP-CUSTOMER-IDENTIFIER
        in: header
        description: Pass this header to search the customer based on their email, mobile number, card
          number or external ID.
        schema:
          type: string
          enum:
          - email
          - mobile
          - cardNumber
          - externalId
      - name: groupId
        in: query
        description: Badge group ID to which the badge belongs to.
        schema:
          type: string
      - name: lastEarnedOnDate
        in: query
        description: 'Date and time when the badge was awarded to the customer. Time format: Epoch format
          (UNIX timestamp in milliseconds).'
        schema:
          type: number
          format: float
      - name: lastEarnEventDate
        in: query
        description: 'Date and time when a triggering event (transactional or behavioural) occurred, initiating
          the badge earning. Time format: Epoch format (UNIX timestamp in milliseconds).'
        schema:
          type: number
          format: float
      responses:
        '200':
          description: '200'
          content:
            application/json:
              examples:
                available badges:
                  value:
                    data:
                      badges:
                      - badgeMetaId: 67eb99516666db076c3c7519
                        orgId: 100737
                        name: Badge Issue georgetest
                        description: Make 5 transactions
                        startOn: 1735715131.0
                        expiresOn: 1926235957.0
                        images:
                        - name: Issued
                          fileSvcHandle: qwer-8634-8938
                          url: https://firebasestorage.googleapis.com/v0/b/createbadges.appspot.com/o/images%2Fsuccess1.jpg?alt=media&token=66b2f0bc-9c55-4e33-a5e9-c6be96d94f2d
                          tag: EARNED
                        tags: []
                        badgeGroupId: null
                        badgeGroupName: null
                        badgeRank: 3
                        ownership:
                          restrictedToOwners:
                          - Milestones
                          - Audience_Campaigns
                          - Historical_Import
                          - Journeys
                          - Loyalty
                          - Rewards_Catalog
                          - Loyalty_Promotion
                          - Goodwill_Module
                          - Referral_Campaigns
                          claims:
                          - ownerType: Loyalty
                            referenceId: '1234'
                            isActive: true
                        earnType: ISSUE_EARN
                        benefits:
                        - benefitType: COUPON
                          seriesId: 13745
                        customerConstraints:
                        - constraintType: CUSTOMER_BADGE_FIXED_WINDOW
                          referenceId: e6791ec9-e92f-34af-bdc3-be2607fdf82c
                          durationType: DAYS
                          refreshRate: 3
                          maxEarnLimit: 2
                          cycleStatus: ACTIVE
                          startDate: 1735715131.0
                          endDate: 1926235957.0
                        badgeConstraints:
                        - constraintType: BADGE_FIXED_VALUE
                          maxEarnLimit: 10000
                        - constraintType: BADGE_ROLLING_WINDOW
                          rollType: WEEKS
                          rollValue: 1
                          maxEarnLimit: 3000
                        - constraintType: BADGE_ROLLING_WINDOW
                          rollType: DAYS
                          rollValue: 1
                          maxEarnLimit: 300
                        earnedCount: null
                        lastEarnedOnDate: null
                        lastEarnEventDate: null
                        customFields: {}
                        active: true
                      - badgeMetaId: 67eb95754c0c691f66b39b50
                        orgId: 100737
                        name: Badge Issue Test
                        description: Make 5 transactions
                        startOn: 1716803487.0
                        expiresOn: 1926235957.0
                        images: []
                        tags: []
                        badgeGroupId: null
                        badgeGroupName: null
                        badgeRank: 3
                        ownership:
                          restrictedToOwners:
                          - Audience_Campaigns
                          claims: []
                        earnType: ISSUE_EARN
                        benefits: []
                        customerConstraints: []
                        badgeConstraints: []
                        earnedCount: null
                        lastEarnedOnDate: null
                        lastEarnEventDate: null
                        customFields: {}
                        active: true
                      - badgeMetaId: 67eb912a4c0c691f66b39b37
                        orgId: 100737
                        name: BadgeISSUAL33
                        description: Make 5 transactions
                        startOn: 1716803487.0
                        expiresOn: 1926235957.0
                        images: []
                        tags: []
                        badgeGroupId: null
                        badgeGroupName: null
                        badgeRank: 3
                        ownership:
                          restrictedToOwners:
                          - Audience_Campaigns
                          claims: []
                        earnType: ISSUE_EARN
                        benefits: []
                        customerConstraints: []
                        badgeConstraints: []
                        earnedCount: null
                        lastEarnedOnDate: null
                        lastEarnEventDate: null
                        customFields: {}
                        active: true
                      - badgeMetaId: 67eb889a6666db076c3c74ac
                        orgId: 100737
                        name: BadgeISSUALGEORGE
                        description: Make 5 transactions
                        startOn: 1716803487.0
                        expiresOn: 1926235957.0
                        images: []
                        tags: []
                        badgeGroupId: null
                        badgeGroupName: null
                        badgeRank: 3
                        ownership:
                          restrictedToOwners:
                          - Audience_Campaigns
                          claims: []
                        earnType: ISSUE_EARN
                        benefits: []
                        customerConstraints: []
                        badgeConstraints: []
                        earnedCount: null
                        lastEarnedOnDate: null
                        lastEarnEventDate: null
                        customFields: {}
                        active: true
                      - badgeMetaId: 6790be86dfc7ed27674ac0d8
                        orgId: 100737
                        name: BadgeDoc
                        description: null
                        startOn: 1737657000.0
                        expiresOn: 1745519399.0
                        images: []
                        tags: []
                        badgeGroupId: null
                        badgeGroupName: null
                        badgeRank: null
                        ownership:
                          restrictedToOwners:
                          - Audience_Campaigns
                          claims: []
                        earnType: EARN
                        benefits: []
                        customerConstraints: []
                        badgeConstraints: []
                        earnedCount: null
                        lastEarnedOnDate: null
                        lastEarnEventDate: null
                        customFields: {}
                        active: true
                      pagination:
                        page: 0
                        size: 5
                        total: 5
                        totalPages: 1
                    errors: []
                    warnings: []
                earned badges:
                  value:
                    data:
                      badges:
                      - badgeMetaId: 67eb9e2d6666db076c3c7556
                        orgId: 100737
                        name: Badge Issue georgetesst
                        description: Make 5 transactions
                        startOn: 1735715131.0
                        expiresOn: 1764572731.0
                        images:
                        - name: Issued
                          fileSvcHandle: qwer-8634-8938
                          url: https://firebasestorage.googleapis.com/v0/b/createbadges.appspot.com/o/images%2Fsuccess1.jpg?alt=media&token=66b2f0bc-9c55-4e33-a5e9-c6be96d94f2d
                          tag: EARNED
                        tags: []
                        badgeGroupId: null
                        badgeGroupName: null
                        badgeRank: 3
                        ownership:
                          restrictedToOwners:
                          - Milestones
                          - Audience_Campaigns
                          - Historical_Import
                          - Journeys
                          - Loyalty
                          - Rewards_Catalog
                          - Loyalty_Promotion
                          - Goodwill_Module
                          - Referral_Campaigns
                          claims:
                          - ownerType: Loyalty
                            referenceId: '12341234'
                            isActive: true
                        earnType: ISSUE_EARN
                        benefits:
                        - benefitType: COUPON
                          seriesId: 13745
                        customerConstraints:
                        - constraintType: CUSTOMER_BADGE_FIXED_WINDOW
                          referenceId: e6791ec9-e92f-34af-bdc3-be2607fdf82c
                          durationType: DAYS
                          refreshRate: 3
                          maxEarnLimit: 2
                          cycleStatus: ACTIVE
                          startDate: 1735715131.0
                          endDate: 1926235957.0
                        badgeConstraints:
                        - constraintType: BADGE_FIXED_VALUE
                          maxEarnLimit: 10000
                        - constraintType: BADGE_ROLLING_WINDOW
                          rollType: WEEKS
                          rollValue: 1
                          maxEarnLimit: 3000
                        - constraintType: BADGE_ROLLING_WINDOW
                          rollType: DAYS
                          rollValue: 1
                          maxEarnLimit: 300
                        earnedCount: 1
                        lastEarnedOnDate: 1743494923.451
                        lastEarnEventDate: 1743494913.679
                        customFields: {}
                        active: true
                      pagination:
                        page: 0
                        size: 1
                        total: 1
                        totalPages: 1
                    errors: []
                    warnings: []
                Sample response with filter by group ID:
                  value:
                    data:
                      badges:
                      - badgeMetaId: 6982d524d93043084c6c3472
                        orgId: 100737
                        name: George
                        description: erg
                        startOn: 1770143400
                        startOnISO: '2026-02-03T18:30:00Z'
                        expiresOn: 1774376999
                        expiresOnISO: '2026-03-24T18:29:59Z'
                        images: []
                        tags: []
                        badgeGroupId: 690874cd2814b4096eba3662
                        badgeGroupName: '45345545445435'
                        badgeRank: 2
                        ownership:
                          restrictedToOwners:
                          - Loyalty
                          claims: []
                        earnType: EARN
                        benefits: []
                        customerConstraints: []
                        badgeConstraints: []
                        earnedCount: null
                        lastEarnedOnDate: null
                        lastEarnedOnDateISO: null
                        lastEarnEventDate: null
                        lastEarnEventDateISO: null
                        customFields:
                          CF 04: '1234'
                          Badge use: uses
                          CF 05: '1234'
                          CF07: 'true'
                          CF31 date: 'false'
                          CF 09: 'null'
                          CF 177: '0'
                          Test CF 01: '0'
                          Test CF: 'null'
                        active: true
                      pagination:
                        page: 0
                        size: 1
                        total: 1
                        totalPages: 1
                    errors: []
                    warnings: []
                  summary: Sample response with filter by group ID
              schema:
                oneOf:
                - title: available badges
                  type: object
                  properties:
                    data:
                      type: object
                      properties:
                        badges:
                          type: array
                          items:
                            type: object
                            properties:
                              badgeMetaId:
                                type: string
                                example: 67eb99516666db076c3c7519
                              orgId:
                                type: integer
                                example: 100737
                                default: 0
                              name:
                                type: string
                                example: Badge Issue georgetest
                              description:
                                type: string
                                example: Make 5 transactions
                              startOn:
                                type: integer
                                example: 1735715131
                                default: 0
                              expiresOn:
                                type: integer
                                example: 1926235957
                                default: 0
                              images:
                                type: array
                                items:
                                  type: object
                                  properties:
                                    name:
                                      type: string
                                      example: Issued
                                    fileSvcHandle:
                                      type: string
                                      example: qwer-8634-8938
                                    url:
                                      type: string
                                      example: https://firebasestorage.googleapis.com/v0/b/createbadges.appspot.com/o/images%2Fsuccess1.jpg?alt=media&token=66b2f0bc-9c55-4e33-a5e9-c6be96d94f2d
                                    tag:
                                      type: string
                                      example: EARNED
                              tags:
                                type: array
                              badgeGroupId: {}
                              badgeGroupName: {}
                              badgeRank:
                                type: integer
                                example: 3
                                default: 0
                              ownership:
                                type: object
                                properties:
                                  restrictedToOwners:
                                    type: array
                                    items:
                                      type: string
                                      example: Milestones
                                  claims:
                                    type: array
                                    items:
                                      type: object
                                      properties:
                                        ownerType:
                                          type: string
                                          example: Loyalty
                                        referenceId:
                                          type: string
                                          example: '1234'
                                        isActive:
                                          type: boolean
                                          example: true
                                          default: true
                              earnType:
                                type: string
                                example: ISSUE_EARN
                              benefits:
                                type: array
                                items:
                                  type: object
                                  properties:
                                    benefitType:
                                      type: string
                                      example: COUPON
                                    seriesId:
                                      type: integer
                                      example: 13745
                                      default: 0
                              customerConstraints:
                                type: array
                                items:
                                  type: object
                                  properties:
                                    constraintType:
                                      type: string
                                      example: CUSTOMER_BADGE_FIXED_WINDOW
                                    referenceId:
                                      type: string
                                      example: e6791ec9-e92f-34af-bdc3-be2607fdf82c
                                    durationType:
                                      type: string
                                      example: DAYS
                                    refreshRate:
                                      type: integer
                                      example: 3
                                      default: 0
                                    maxEarnLimit:
                                      type: integer
                                      example: 2
                                      default: 0
                                    cycleStatus:
                                      type: string
                                      example: ACTIVE
                                    startDate:
                                      type: integer
                                      example: 1735715131
                                      default: 0
                                    endDate:
                                      type: integer
                                      example: 1926235957
                                      default: 0
                              badgeConstraints:
                                type: array
                                items:
                                  type: object
                                  properties:
                                    constraintType:
                                      type: string
                                      example: BADGE_FIXED_VALUE
                                    maxEarnLimit:
                                      type: integer
                                      example: 10000
                                      default: 0
                              earnedCount: {}
                              lastEarnedOnDate: {}
                              lastEarnEventDate: {}
                              customFields:
                                type: object
                                properties: {}
                              active:
                                type: boolean
                                example: true
                                default: true
                        pagination:
                          type: object
                          properties:
                            page:
                              type: integer
                              example: 0
                              default: 0
                            size:
                              type: integer
                              example: 5
                              default: 0
                            total:
                              type: integer
                              example: 5
                              default: 0
                            totalPages:
                              type: integer
                              example: 1
                              default: 0
                    errors:
                      type: array
                    warnings:
                      type: array
                - title: earned badges
                  type: object
                  properties:
                    data:
                      type: object
                      properties:
                        badges:
                          type: array
                          items:
                            type: object
                            properties:
                              badgeMetaId:
                                type: string
                                example: 67eb9e2d6666db076c3c7556
                              orgId:
                                type: integer
                                example: 100737
                                default: 0
                              name:
                                type: string
                                example: Badge Issue georgetesst
                              description:
                                type: string
                                example: Make 5 transactions
                              startOn:
                                type: integer
                                example: 1735715131
                                default: 0
                              expiresOn:
                                type: integer
                                example: 1764572731
                                default: 0
                              images:
                                type: array
                                items:
                                  type: object
                                  properties:
                                    name:
                                      type: string
                                      example: Issued
                                    fileSvcHandle:
                                      type: string
                                      example: qwer-8634-8938
                                    url:
                                      type: string
                                      example: https://firebasestorage.googleapis.com/v0/b/createbadges.appspot.com/o/images%2Fsuccess1.jpg?alt=media&token=66b2f0bc-9c55-4e33-a5e9-c6be96d94f2d
                                    tag:
                                      type: string
                                      example: EARNED
                              tags:
                                type: array
                              badgeGroupId: {}
                              badgeGroupName: {}
                              badgeRank:
                                type: integer
                                example: 3
                                default: 0
                              ownership:
                                type: object
                                properties:
                                  restrictedToOwners:
                                    type: array
                                    items:
                                      type: string
                                      example: Milestones
                                  claims:
                                    type: array
                                    items:
                                      type: object
                                      properties:
                                        ownerType:
                                          type: string
                                          example: Loyalty
                                        referenceId:
                                          type: string
                                          example: '12341234'
                                        isActive:
                                          type: boolean
                                          example: true
                                          default: true
                              earnType:
                                type: string
                                example: ISSUE_EARN
                              benefits:
                                type: array
                                items:
                                  type: object
                                  properties:
                                    benefitType:
                                      type: string
                                      example: COUPON
                                    seriesId:
                                      type: integer
                                      example: 13745
                                      default: 0
                              customerConstraints:
                                type: array
                                items:
                                  type: object
                                  properties:
                                    constraintType:
                                      type: string
                                      example: CUSTOMER_BADGE_FIXED_WINDOW
                                    referenceId:
                                      type: string
                                      example: e6791ec9-e92f-34af-bdc3-be2607fdf82c
                                    durationType:
                                      type: string
                                      example: DAYS
                                    refreshRate:
                                      type: integer
                                      example: 3
                                      default: 0
                                    maxEarnLimit:
                                      type: integer
                                      example: 2
                                      default: 0
                                    cycleStatus:
                                      type: string
                                      example: ACTIVE
                                    startDate:
                                      type: integer
                                      example: 1735715131
                                      default: 0
                                    endDate:
                                      type: integer
                                      example: 1926235957
                                      default: 0
                              badgeConstraints:
                                type: array
                                items:
                                  type: object
                                  properties:
                                    constraintType:
                                      type: string
                                      example: BADGE_FIXED_VALUE
                                    maxEarnLimit:
                                      type: integer
                                      example: 10000
                                      default: 0
                              earnedCount:
                                type: integer
                                example: 1
                                default: 0
                              lastEarnedOnDate:
                                type: number
                                example: 1743494923.451
                                default: 0
                              lastEarnEventDate:
                                type: number
                                example: 1743494913.679
                                default: 0
                              customFields:
                                type: object
                                properties: {}
                              active:
                                type: boolean
                                example: true
                                default: true
                        pagination:
                          type: object
                          properties:
                            page:
                              type: integer
                              example: 0
                              default: 0
                            size:
                              type: integer
                              example: 1
                              default: 0
                            total:
                              type: integer
                              example: 1
                              default: 0
                            totalPages:
                              type: integer
                              example: 1
                              default: 0
                    errors:
                      type: array
                    warnings:
                      type: array
                - title: Filter by group ID
                  type: object
                  properties:
                    data:
                      type: object
                      properties:
                        badges:
                          type: array
                          items:
                            type: object
                            properties:
                              badgeMetaId:
                                type: string
                                example: 653dea07b3cda7078c7c68ee
                              orgId:
                                type: integer
                                example: 100606
                                default: 0
                              name:
                                type: string
                                example: Birthday Badge
                              description:
                                type: string
                                example: Make a purchase during your birthday month and get a 40% discount
                                  coupon
                              startOn:
                                type: integer
                                example: 1698557400
                                default: 0
                              expiresOn:
                                type: integer
                                example: 4872129400
                                default: 0
                              images:
                                type: array
                                items:
                                  type: object
                                  properties:
                                    name:
                                      type: string
                                      example: ''
                                    fileSvcHandle:
                                      type: string
                                      example: 8be2b78e-b1d6-4127-926a-2cbed7eb2785
                                    url:
                                      type: string
                                      example: https://storage.crm.eu.content-cdn.io/fs.capillary.eu/incentives_assets/badges/images/100606/653dea07b3cda7078c7c68ee_UN_EARNED_vDx_DRdk.png
                                    tag:
                                      type: string
                                      example: UN_EARNED
                              badgeGroupId:
                                type: string
                                example: 65c3600c60d9261bdd8a6410
                              badgeGroupName:
                                type: string
                                example: 2024 Badges
                              badgeRank:
                                type: integer
                                example: 2
                                default: 0
                              ownership:
                                type: object
                                properties:
                                  restrictedToOwners:
                                    type: array
                                    items:
                                      type: string
                                      example: Loyalty
                                  claims:
                                    type: array
                                    items:
                                      type: object
                                      properties:
                                        ownerType:
                                          type: string
                                          example: Loyalty
                                        referenceId:
                                          type: string
                                          example: '626'
                                        isActive:
                                          type: boolean
                                          example: true
                                          default: true
                              earnType:
                                type: string
                                example: ISSUE_EARN
                              customerConstraints:
                                type: array
                                items:
                                  type: object
                                  properties:
                                    constraintType:
                                      type: string
                                      example: CUSTOMER_BADGE_FIXED_VALUE
                                    maxEarnLimit:
                                      type: integer
                                      example: 1
                                      default: 0
                              badgeConstraints:
                                type: array
                              earnedCount: {}
                              customFields:
                                type: object
                                properties:
                                  '2024':
                                    type: string
                                    example: 'true'
                                  Date:
                                    type: string
                                    example: '2025-01-18 14:39:09'
                                  Category1:
                                    type: string
                                    example: 'false'
                                  Priority:
                                    type: string
                                    example: '1'
                              active:
                                type: boolean
                                example: true
                                default: true
                        pagination:
                          type: object
                          properties:
                            page:
                              type: integer
                              example: 0
                              default: 0
                            size:
                              type: integer
                              example: 1
                              default: 0
                            total:
                              type: integer
                              example: 1
                              default: 0
                            totalPages:
                              type: integer
                              example: 1
                              default: 0
                    errors:
                      type: array
                    warnings:
                      type: array
      deprecated: false
      x-readme:
        code-samples:
        - language: curl
          code: |-
            curl --location 'https://eu.api.capillarytech.com/api_gateway/v1/badges/customer/565039504' \
            --header 'Accept: application/json' \
            --header 'Content-Type: application/json' \
            --header 'accept: application/json' \
            --header 'Authorization: Basic Z2VvcmdlLmpvaG5zb246OTg4OTU2NWI4ODVhMmY4ZWE1MTk1MjA2NWEwYTEzNzg=' \
            --header 'Cookie: _cfuvid=pDcK3FYcGs86zaO.Nm3dErmATpyR5j3nnGAtlkTM0Sk-1745211210745-0.0.1.1-604800000'
          name: Example request
        - language: curl
          code: https://eucrm.cc.capillarytech.com/api_gateway/v1/badges/customer/tom.sawyer@capillarytech.com
          name: Example request using the header
        - language: curl
          code: |-
            curl --location 'https://eu.api.capillarytech.com/api_gateway/v1/badges/customer/566881933?groupId=690874cd2814b4096eba3662' \
            --header 'Accept: application/json' \
            --header 'Content-Type: application/json' \
            --header 'accept: application/json' \
            --header 'Authorization: Basic bWFkaHVfoI3MjU2YQ==' \
            --header 'Cookie: _cfuvid=pDcK3FYcGs86zaO.Nm3dErmATpyR5j3nnGAtlkTM0Sk-1745211210745-0.0.1.1-604800000; _cfuvid=I_dbNMPLOmRfzPQyzR9DnX8lpYlzQ6p6AY5ZrM1UpaM-1770891499083-0.0.1.1-604800000'
          name: Sample Example request with group ID filter
        samples-languages:
        - curl
components:
  securitySchemes:
    sec0:
      type: http
      scheme: basic
