openapi: 3.1.0
info:
  title: Get Reward Expiry Reminder
  version: '1.0'
servers:
- url: https://{host}
  variables:
    host:
      default: host
security:
- sec0: []
paths:
  /api_gateway/rewards/core/v1/reward/expiryReminder:
    get:
      summary: Get Reward Expiry Reminder
      description: ''
      operationId: get-reward-expiry-reminder
      parameters:
      - name: filter
        in: query
        description: Filters the active or inactive reward expiry reminder.
        schema:
          type: boolean
      - name: page
        in: query
        description: The amount of the data that you want to retrieve.
        schema:
          type: integer
          format: int32
      - name: size
        in: query
        description: The number of items or records returned in a single API response.
        schema:
          type: integer
          format: int32
      responses:
        '200':
          description: '200'
          content:
            application/json:
              examples:
                Result:
                  value:
                    rewardExpiryReminder:
                    - id: 5
                      orgId: 100458
                      duration: 15
                      durationType: DAYS
                      cronTaskId: 590567
                      timing: '12:00'
                      isActive: true
                      createdOn: 1727681940000
                      lastUpdatedOn: 1727681946000
                      createdBy: 75130850
                      lastUpdatedBy: 75130850
                    - id: 2
                      orgId: 100458
                      duration: 15
                      durationType: DAYS
                      cronTaskId: 590564
                      timing: '12:00'
                      isActive: true
                      createdOn: 1727680228000
                      lastUpdatedOn: 1727681674000
                      createdBy: 75130850
                      lastUpdatedBy: 75130850
                    - id: 4
                      orgId: 100458
                      duration: 32
                      durationType: DAYS
                      cronTaskId: 590566
                      timing: '18:00'
                      isActive: true
                      createdOn: 1727681405000
                      lastUpdatedOn: 1727681405000
                      createdBy: 75130850
                      lastUpdatedBy: 75130850
                    - id: 3
                      orgId: 100458
                      duration: 32
                      durationType: DAYS
                      cronTaskId: 590565
                      timing: '18:00'
                      isActive: true
                      createdOn: 1727680457000
                      lastUpdatedOn: 1727680457000
                      createdBy: 75130850
                      lastUpdatedBy: 75130850
                    pagingDto:
                      last: true
                      totalElements: 4
                      totalPages: 1
                      numberOfElements: 4
                      first: true
                      size: 10
                      number: 0
              schema:
                type: object
                properties:
                  rewardExpiryReminder:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 5
                          default: 0
                        orgId:
                          type: integer
                          example: 100458
                          default: 0
                        duration:
                          type: integer
                          example: 15
                          default: 0
                        durationType:
                          type: string
                          example: DAYS
                        cronTaskId:
                          type: integer
                          example: 590567
                          default: 0
                        timing:
                          type: string
                          example: '12:00'
                        isActive:
                          type: boolean
                          example: true
                          default: true
                        createdOn:
                          type: integer
                          example: 1727681940000
                          default: 0
                        lastUpdatedOn:
                          type: integer
                          example: 1727681946000
                          default: 0
                        createdBy:
                          type: integer
                          example: 75130850
                          default: 0
                        lastUpdatedBy:
                          type: integer
                          example: 75130850
                          default: 0
                  pagingDto:
                    type: object
                    properties:
                      last:
                        type: boolean
                        example: true
                        default: true
                      totalElements:
                        type: integer
                        example: 4
                        default: 0
                      totalPages:
                        type: integer
                        example: 1
                        default: 0
                      numberOfElements:
                        type: integer
                        example: 4
                        default: 0
                      first:
                        type: boolean
                        example: true
                        default: true
                      size:
                        type: integer
                        example: 10
                        default: 0
                      number:
                        type: integer
                        example: 0
                        default: 0
        '400':
          description: '400'
          content:
            application/json:
              examples:
                Size should be >=1:
                  value:
                    status:
                      success: false
                      code: 400
                      message: size should be greater or equal to 1.
                page should be >=0:
                  value:
                    status:
                      success: false
                      code: 400
                      message: page should be greater or equal to 0.
              schema:
                oneOf:
                - title: Size should be >=1
                  type: object
                  properties:
                    status:
                      type: object
                      properties:
                        success:
                          type: boolean
                          example: false
                          default: true
                        code:
                          type: integer
                          example: 400
                          default: 0
                        message:
                          type: string
                          example: size should be greater or equal to 1.
                - title: page should be >=0
                  type: object
                  properties:
                    status:
                      type: object
                      properties:
                        success:
                          type: boolean
                          example: false
                          default: true
                        code:
                          type: integer
                          example: 400
                          default: 0
                        message:
                          type: string
                          example: page should be greater or equal to 0.
      deprecated: false
      x-readme:
        code-samples:
        - language: curl
          code: |-
            curl --location 'https://eu.api.capillarytech.com/api_gateway/rewards/core/v1/reward/expiryReminder?filter=ACTIVE&size=10&page=0' \
            --header 'Content-Type: application/json' \
            --header 'Authorization: Basic aWFtc2hpdmFhbblahblahZjhlMzRkNWI1YTI5MWY=' \
            --header 'user-agent: pyapps_auto_2024-05-25-12-47-39' \
            --header 'Cookie: _cfuvid=EdYU22mJWP1xzoxt74hggY7PKdhUOcIzYPQlaq4bOyU-1727677397251-0.0.1.1-604800000'
        samples-languages:
        - curl
components:
  securitySchemes:
    sec0:
      type: http
      scheme: basic
