openapi: 3.1.0
info:
  title: Issue Reward in connected orgs
  version: '1.0'
servers:
- url: https://{host}
  variables:
    host:
      default: host
security:
- sec0: []
paths:
  /v1.1/user/rewards/issue/:
    post:
      summary: Issue Reward in connected orgs
      description: ''
      operationId: issue-bulk-reward-connected-org
      parameters:
      - name: username
        in: query
        description: username here represents name of the store
        required: true
        schema:
          type: string
          default: store_name
      - name: skip_validation
        in: query
        description: optional
        schema:
          type: string
      - name: till
        in: query
        schema:
          type: string
        required: false
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                mobile:
                  type: string
                  description: Mobile number/ email Id/ External Id of the customer
                brand:
                  type: string
                  description: name of the brand
                transactionNumber:
                  type: string
                  description: transaction number for issuing the reward
                rewardId:
                  type: string
                  description: reward ID(s) of the rewards to be issued
      responses:
        '200':
          description: '200'
          content:
            application/json:
              examples:
                With DATA-SCOPE as SELF:
                  value:
                    status:
                      success: true
                      code: 200
                      message: Reward issued successfully
                    rewards:
                    - status:
                        success: true
                        code: 200
                        message: Reward issued successfully
                      orgId: 4004543
                      transactionId: 57097
                      rewardId: 350
                      requestedQuantity: 1
                      quantity: 1
                      pointsReferenceId: 7Scaq1
                      pointsReferenceIds:
                      - 7Scaq1
                      eventLogId: null
                      requestId: null
                      intouch: null
                      promotions: []
                      vendor:
                      - valid_till: '2027-11-01'
                        voucher: OV4GJYQV3Y
                        pointsRedeemed: '2'
                        offer_name: marvel-loadtest
                        coupon_series_id: '234'
                      restrictions: null
                      paymentConfig:
                        paymentMode: CONV_RATIO
                        id: 54
                        conversionRatio: 0.5
                      fulfillmentDetails: null
                      customFields: null
                      redemptionDetails:
                        redemptionType: MILES
                        totalRedemptionValue: 1
                With DATA-SCOPE as OTHER:
                  value:
                    status:
                      success: true
                      code: 200
                      message: Reward issued successfully
                    rewards:
                    - status:
                        success: true
                        code: 200
                        message: Reward issued successfully
                      orgId: 4000086
                      transactionId: 57097
                      rewardId: 350
                      requestedQuantity: 1
                      quantity: 1
                      pointsReferenceId: 7Scaq1
                      pointsReferenceIds:
                      - 7Scaq1
                      eventLogId: null
                      requestId: null
                      intouch: null
                      promotions: []
                      vendor:
                      - valid_till: '2027-11-01'
                        voucher: OV4GJYQV3Y
                        pointsRedeemed: '2'
                        offer_name: marvel-loadtest
                        coupon_series_id: '234'
                      restrictions: null
                      paymentConfig:
                        paymentMode: CONV_RATIO
                        id: 54
                        conversionRatio: 0.5
                      fulfillmentDetails: null
                      customFields: null
                      redemptionDetails:
                        redemptionType: MILES
                        totalRedemptionValue: 1
              schema:
                oneOf:
                - title: With DATA-SCOPE as SELF
                  type: object
                  properties:
                    status:
                      type: object
                      properties:
                        success:
                          type: boolean
                          example: true
                          default: true
                        code:
                          type: integer
                          example: 200
                          default: 0
                        message:
                          type: string
                          example: Reward issued successfully
                    rewards:
                      type: array
                      items:
                        type: object
                        properties:
                          status:
                            type: object
                            properties:
                              success:
                                type: boolean
                                example: true
                                default: true
                              code:
                                type: integer
                                example: 200
                                default: 0
                              message:
                                type: string
                                example: Reward issued successfully
                          orgId:
                            type: integer
                            example: 4004543
                            default: 0
                          transactionId:
                            type: integer
                            example: 57097
                            default: 0
                          rewardId:
                            type: integer
                            example: 350
                            default: 0
                          requestedQuantity:
                            type: integer
                            example: 1
                            default: 0
                          quantity:
                            type: integer
                            example: 1
                            default: 0
                          pointsReferenceId:
                            type: string
                            example: 7Scaq1
                          pointsReferenceIds:
                            type: array
                            items:
                              type: string
                              example: 7Scaq1
                          eventLogId: {}
                          requestId: {}
                          intouch: {}
                          promotions:
                            type: array
                          vendor:
                            type: array
                            items:
                              type: object
                              properties:
                                valid_till:
                                  type: string
                                  example: '2027-11-01'
                                voucher:
                                  type: string
                                  example: OV4GJYQV3Y
                                pointsRedeemed:
                                  type: string
                                  example: '2'
                                offer_name:
                                  type: string
                                  example: marvel-loadtest
                                coupon_series_id:
                                  type: string
                                  example: '234'
                          restrictions: {}
                          paymentConfig:
                            type: object
                            properties:
                              paymentMode:
                                type: string
                                example: CONV_RATIO
                              id:
                                type: integer
                                example: 54
                                default: 0
                              conversionRatio:
                                type: number
                                example: 0.5
                                default: 0
                          fulfillmentDetails: {}
                          customFields: {}
                          redemptionDetails:
                            type: object
                            properties:
                              redemptionType:
                                type: string
                                example: MILES
                              totalRedemptionValue:
                                type: integer
                                example: 1
                                default: 0
                - title: With DATA-SCOPE as OTHER
                  type: object
                  properties:
                    status:
                      type: object
                      properties:
                        success:
                          type: boolean
                          example: true
                          default: true
                        code:
                          type: integer
                          example: 200
                          default: 0
                        message:
                          type: string
                          example: Reward issued successfully
                    rewards:
                      type: array
                      items:
                        type: object
                        properties:
                          status:
                            type: object
                            properties:
                              success:
                                type: boolean
                                example: true
                                default: true
                              code:
                                type: integer
                                example: 200
                                default: 0
                              message:
                                type: string
                                example: Reward issued successfully
                          orgId:
                            type: integer
                            example: 4000086
                            default: 0
                          transactionId:
                            type: integer
                            example: 57097
                            default: 0
                          rewardId:
                            type: integer
                            example: 350
                            default: 0
                          requestedQuantity:
                            type: integer
                            example: 1
                            default: 0
                          quantity:
                            type: integer
                            example: 1
                            default: 0
                          pointsReferenceId:
                            type: string
                            example: 7Scaq1
                          pointsReferenceIds:
                            type: array
                            items:
                              type: string
                              example: 7Scaq1
                          eventLogId: {}
                          requestId: {}
                          intouch: {}
                          promotions:
                            type: array
                          vendor:
                            type: array
                            items:
                              type: object
                              properties:
                                valid_till:
                                  type: string
                                  example: '2027-11-01'
                                voucher:
                                  type: string
                                  example: OV4GJYQV3Y
                                pointsRedeemed:
                                  type: string
                                  example: '2'
                                offer_name:
                                  type: string
                                  example: marvel-loadtest
                                coupon_series_id:
                                  type: string
                                  example: '234'
                          restrictions: {}
                          paymentConfig:
                            type: object
                            properties:
                              paymentMode:
                                type: string
                                example: CONV_RATIO
                              id:
                                type: integer
                                example: 54
                                default: 0
                              conversionRatio:
                                type: number
                                example: 0.5
                                default: 0
                          fulfillmentDetails: {}
                          customFields: {}
                          redemptionDetails:
                            type: object
                            properties:
                              redemptionType:
                                type: string
                                example: MILES
                              totalRedemptionValue:
                                type: integer
                                example: 1
                                default: 0
        '400':
          description: '400'
          content:
            application/json:
              examples:
                '8003':
                  value:
                    status:
                      success: false
                      code: 8003
                      message: fail to issue reward
                    rewards:
                    - status:
                        success: false
                        code: 12005
                        message: Reward constraint evaluation failed. Request failed. Max limit for the
                          DAYS is reached. Allowed limit is 15 For Level CUSTOMER
                      rewardId: 49827
                      requestedQuantity: 1
                      pointsReferenceId: null
                      intouch: null
                      promotions: null
                      vendor: null
                      restrictions: null
                Result:
                  value:
                    status:
                      success: false
                      code: 8010
                      message: Reward issued partially
                    rewards:
                    - status:
                        success: true
                        code: 200
                        message: Reward issued successfully
                      rewardId: 13
                      requestedQuantity: 1
                      pointsReferenceId: ZGxGVD
                      intouch:
                      - pointsRedeemed: '50'
                        couponCode: 42FU1ZP3
                        codeExpiry: '2023-06-09 00:00:00'
                      promotions: []
                      vendor: []
                      restrictions: null
                    - status:
                        success: false
                        code: 8004
                        message: fail to issue reward as  Coupon has expired
                      rewardId: 12
                      requestedQuantity: 1
                      pointsReferenceId: ZGxGVD
                      intouch: null
                      promotions: []
                      vendor: []
                      restrictions: null
              schema:
                oneOf:
                - type: object
                  properties:
                    status:
                      type: object
                      properties:
                        success:
                          type: boolean
                          example: false
                          default: true
                        code:
                          type: integer
                          example: 8010
                          default: 0
                        message:
                          type: string
                          example: Reward issued partially
                    rewards:
                      type: array
                      items:
                        type: object
                        properties:
                          status:
                            type: object
                            properties:
                              success:
                                type: boolean
                                example: true
                                default: true
                              code:
                                type: integer
                                example: 200
                                default: 0
                              message:
                                type: string
                                example: Reward issued successfully
                          rewardId:
                            type: integer
                            example: 13
                            default: 0
                          requestedQuantity:
                            type: integer
                            example: 1
                            default: 0
                          pointsReferenceId:
                            type: string
                            example: ZGxGVD
                          intouch:
                            type: array
                            items:
                              type: object
                              properties:
                                pointsRedeemed:
                                  type: string
                                  example: '50'
                                couponCode:
                                  type: string
                                  example: 42FU1ZP3
                                codeExpiry:
                                  type: string
                                  example: '2023-06-09 00:00:00'
                          promotions:
                            type: array
                          vendor:
                            type: array
                          restrictions: {}
                - title: '8003'
                  type: object
                  properties:
                    status:
                      type: object
                      properties:
                        success:
                          type: boolean
                          example: false
                          default: true
                        code:
                          type: integer
                          example: 8003
                          default: 0
                        message:
                          type: string
                          example: fail to issue reward
                    rewards:
                      type: array
                      items:
                        type: object
                        properties:
                          status:
                            type: object
                            properties:
                              success:
                                type: boolean
                                example: false
                                default: true
                              code:
                                type: integer
                                example: 12005
                                default: 0
                              message:
                                type: string
                                example: Reward constraint evaluation failed. Request failed. Max limit
                                  for the DAYS is reached. Allowed limit is 15 For Level CUSTOMER
                          rewardId:
                            type: integer
                            example: 49827
                            default: 0
                          requestedQuantity:
                            type: integer
                            example: 1
                            default: 0
                          pointsReferenceId: {}
                          intouch: {}
                          promotions: {}
                          vendor: {}
                          restrictions: {}
      deprecated: false
      x-readme:
        code-samples:
        - language: curl
          code: |-
            curl --location 'https://eu.api.capillarytech.com/api_gateway/rewards/core/v1.1/user/rewards/issue/?skip_validation=true&username=loadtest.marvel' \
            --header 'Content-Type: application/json' \
            --header 'Accept: */*' \
            --header 'Authorization: Basic bG9hZHRlc3QubWBLAHBLAH5NjRiMDcxNTJkMjM0Yjcw' \
            --header 'Cookie: _cfuvid=Vl2GkTHlFJ52__EqmWxwr62UUys6VkoqjLDZ8Iah00s-1732168027696-0.0.1.1-604800000; _cfuvid=iCEn1_39ZRrYViEvmJGle4eW7lcuck3DPgT_B1jmysQ-1732599277239-0.0.1.1-604800000' \
            --header 'DATA-SCOPE: SELF' \
            --data '{
                "brand": "O2Brand",
                "transactionNumber": "123456789",
                "orgLevelDetails": [
                    {
                        "orgId": 4004543
                    }
                ],
                "rewards": [
                    {
                        "rewardId": 350,
                        "quantity": 1,
                        "orgId": 4004543,
                        "paymentConfig": {
                            "redemptionValue": 1
                        }
                    }
                ],
                "externalId": "ext_id9860000198"
            }'
          name: With DATA-SCOPE as SELF
        - language: curl
          code: |-
            curl --location 'https://eu.api.capillarytech.com/api_gateway/rewards/core/v1.1/user/rewards/issue/?skip_validation=true&username=loadtest.marvel' \
            --header 'Content-Type: application/json' \
            --header 'Accept: */*' \
            --header 'Authorization: Basic bG9hZHBLAHBLAH3NWI5NjRiMDcxNTJkMjM0Yjcw' \
            --header 'DATA-SCOPE: OTHER' \
            --header 'DATA-SCOPE-ORGS: 4000085' \
            --header 'Cookie: _cfuvid=u7lX7fA.uTQht8cWKxG4HXhwZo7y8PLo9hFe64KkyjA-1734592157810-0.0.1.1-604800000' \
            --data '{
                "brand": "OptumUATChild2",
                "transactionNumber": "123456789",
                "orgLevelDetails": [
                    {
                        "orgId": 4000086
                    }
                ],
                "rewards": [
                    {
                        "rewardId": 350,
                        "quantity": 1,
                        "orgId": 4000086,
                        "paymentConfig": {
                            "redemptionValue": 1
                        }
                    }
                ],
                "externalId": "ext_id9860000198"
            }'
          name: With DATA-SCOPE as OTHER
        samples-languages:
        - curl
components:
  securitySchemes:
    sec0:
      type: http
      scheme: basic
