openapi: 3.1.0
info:
  title: Issue bulk reward
  version: '1.0'
servers:
- url: https://{host}
  variables:
    host:
      default: host
security:
- sec0: []
paths:
  /api_gateway/rewards/core/v1/user/rewards/issue:
    post:
      summary: Issue bulk reward
      description: ''
      operationId: issue-bulk-reward
      parameters:
      - name: username
        in: query
        description: username here represents name of the store
        required: true
        schema:
          type: string
          default: store_name
      - name: skip_validation
        in: query
        description: optional
        schema:
          type: string
      - name: store
        in: query
        schema:
          type: string
        required: false
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                mobile:
                  type: string
                  description: Mobile number/ email Id/ External Id of the customer
                brand:
                  type: string
                  description: name of the brand
                transactionNumber:
                  type: string
                  description: transaction number for issuing the reward
                rewardId:
                  type: string
                  description: reward ID(s) of the rewards to be issued
      responses:
        '200':
          description: '200'
          content:
            application/json:
              examples:
                Result:
                  value:
                    status:
                      success: true
                      code: 200
                      message: Reward issued successfully
                    rewards:
                    - status:
                        success: false
                        code: 8010
                        message: Reward issued partially
                      transactionId: 397107
                      rewardId: 225086
                      requestedQuantity: 1
                      quantity: 2
                      pointsReferenceId: null
                      pointsReferenceIds: []
                      eventLogId: null
                      requestId: null
                      intouch:
                      - pointsRedeemed: '0'
                        couponCode: '1908009843'
                        codeExpiry: '2025-10-31 00:00:00'
                        codeExpiryDateTime: '2025-10-31T00:00:00Z'
                      - pointsRedeemed: '0'
                        couponCode: '2088404495'
                        codeExpiry: '2025-10-31 00:00:00'
                        codeExpiryDateTime: '2025-10-31T00:00:00Z'
                      promotions: []
                      vendor: []
                      eventDateTime: '2025-05-08T13:48:13Z'
                      restrictions: null
                      paymentConfig:
                        paymentMode: FREE
                        id: 463
                      fulfillmentDetails: null
                      customFields: null
                      redemptionDetails: null
                    - status:
                        success: false
                        code: 8003
                        message: fail to issue reward
                      transactionId: 397108
                      rewardId: 225087
                      requestedQuantity: 1
                      quantity: 0
                      pointsReferenceId: null
                      pointsReferenceIds: []
                      eventLogId: null
                      requestId: null
                      intouch: null
                      promotions: []
                      vendor: []
                      eventDateTime: '2025-05-08T13:48:13Z'
                      restrictions: null
                      paymentConfig:
                        paymentMode: FREE
                        id: 464
                      fulfillmentDetails: null
                      customFields: null
                      redemptionDetails: null
              schema:
                type: object
                properties:
                  status:
                    type: object
                    properties:
                      success:
                        type: boolean
                        example: true
                        default: true
                      code:
                        type: integer
                        example: 200
                        default: 0
                      message:
                        type: string
                        example: Reward issued successfully
                  rewards:
                    type: array
                    items:
                      type: object
                      properties:
                        status:
                          type: object
                          properties:
                            success:
                              type: boolean
                              example: false
                              default: true
                            code:
                              type: integer
                              example: 8010
                              default: 0
                            message:
                              type: string
                              example: Reward issued partially
                        transactionId:
                          type: integer
                          example: 397107
                          default: 0
                        rewardId:
                          type: integer
                          example: 225086
                          default: 0
                        requestedQuantity:
                          type: integer
                          example: 1
                          default: 0
                        quantity:
                          type: integer
                          example: 2
                          default: 0
                        pointsReferenceId: {}
                        pointsReferenceIds:
                          type: array
                        eventLogId: {}
                        requestId: {}
                        intouch:
                          type: array
                          items:
                            type: object
                            properties:
                              pointsRedeemed:
                                type: string
                                example: '0'
                              couponCode:
                                type: string
                                example: '1908009843'
                              codeExpiry:
                                type: string
                                example: '2025-10-31 00:00:00'
                              codeExpiryDateTime:
                                type: string
                                example: '2025-10-31T00:00:00Z'
                        promotions:
                          type: array
                        vendor:
                          type: array
                        eventDateTime:
                          type: string
                          example: '2025-05-08T13:48:13Z'
                        restrictions: {}
                        paymentConfig:
                          type: object
                          properties:
                            paymentMode:
                              type: string
                              example: FREE
                            id:
                              type: integer
                              example: 463
                              default: 0
                        fulfillmentDetails: {}
                        customFields: {}
                        redemptionDetails: {}
        '400':
          description: '400'
          content:
            application/json:
              examples:
                '8003':
                  value:
                    status:
                      success: false
                      code: 8003
                      message: fail to issue reward
                    rewards:
                    - status:
                        success: false
                        code: 12005
                        message: Reward constraint evaluation failed. Request failed. Max limit for the
                          DAYS is reached. Allowed limit is 15 For Level CUSTOMER
                      rewardId: 49827
                      requestedQuantity: 1
                      pointsReferenceId: null
                      intouch: null
                      promotions: null
                      vendor: null
                      restrictions: null
                Result:
                  value:
                    status:
                      success: false
                      code: 8010
                      message: Reward issued partially
                    rewards:
                    - status:
                        success: true
                        code: 200
                        message: Reward issued successfully
                      rewardId: 13
                      requestedQuantity: 1
                      pointsReferenceId: ZGxGVD
                      intouch:
                      - pointsRedeemed: '50'
                        couponCode: 42FU1ZP3
                        codeExpiry: '2023-06-09 00:00:00'
                      promotions: []
                      vendor: []
                      restrictions: null
                    - status:
                        success: false
                        code: 8004
                        message: fail to issue reward as  Coupon has expired
                      rewardId: 12
                      requestedQuantity: 1
                      pointsReferenceId: ZGxGVD
                      intouch: null
                      promotions: []
                      vendor: []
                      restrictions: null
              schema:
                oneOf:
                - type: object
                  properties:
                    status:
                      type: object
                      properties:
                        success:
                          type: boolean
                          example: false
                          default: true
                        code:
                          type: integer
                          example: 8010
                          default: 0
                        message:
                          type: string
                          example: Reward issued partially
                    rewards:
                      type: array
                      items:
                        type: object
                        properties:
                          status:
                            type: object
                            properties:
                              success:
                                type: boolean
                                example: true
                                default: true
                              code:
                                type: integer
                                example: 200
                                default: 0
                              message:
                                type: string
                                example: Reward issued successfully
                          rewardId:
                            type: integer
                            example: 13
                            default: 0
                          requestedQuantity:
                            type: integer
                            example: 1
                            default: 0
                          pointsReferenceId:
                            type: string
                            example: ZGxGVD
                          intouch:
                            type: array
                            items:
                              type: object
                              properties:
                                pointsRedeemed:
                                  type: string
                                  example: '50'
                                couponCode:
                                  type: string
                                  example: 42FU1ZP3
                                codeExpiry:
                                  type: string
                                  example: '2023-06-09 00:00:00'
                          promotions:
                            type: array
                          vendor:
                            type: array
                          restrictions: {}
                - title: '8003'
                  type: object
                  properties:
                    status:
                      type: object
                      properties:
                        success:
                          type: boolean
                          example: false
                          default: true
                        code:
                          type: integer
                          example: 8003
                          default: 0
                        message:
                          type: string
                          example: fail to issue reward
                    rewards:
                      type: array
                      items:
                        type: object
                        properties:
                          status:
                            type: object
                            properties:
                              success:
                                type: boolean
                                example: false
                                default: true
                              code:
                                type: integer
                                example: 12005
                                default: 0
                              message:
                                type: string
                                example: Reward constraint evaluation failed. Request failed. Max limit
                                  for the DAYS is reached. Allowed limit is 15 For Level CUSTOMER
                          rewardId:
                            type: integer
                            example: 49827
                            default: 0
                          requestedQuantity:
                            type: integer
                            example: 1
                            default: 0
                          pointsReferenceId: {}
                          intouch: {}
                          promotions: {}
                          vendor: {}
                          restrictions: {}
      deprecated: false
      x-readme:
        code-samples:
        - language: curl
          code: ''
          name: request body
        samples-languages:
        - curl
components:
  securitySchemes:
    sec0:
      type: http
      scheme: basic
