openapi: 3.1.0
info:
  title: Create custom field for reward
  version: '1.0'
servers:
- url: https://{host}
  variables:
    host:
      default: host
security:
- sec0: []
paths:
  /api_gateway/rewards/core/v1/brand/customfield:
    post:
      summary: Create custom field for reward
      description: ''
      operationId: post-create-custom-field
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - name
              - description
              - scope
              - dataType
              properties:
                name:
                  type: string
                  description: Unique name identifier for the custom field.
                orgId:
                  type: string
                  description: Unique identifier of the organisation. To retrieve the orgId, use the Get
                    Org Details API.
                description:
                  type: string
                  description: Description for the custom field.
                isMandatory:
                  type: boolean
                  description: Specify if the custom field is mandatory.
                  default: false
                isActive:
                  type: boolean
                  description: Parameter to define if the custom field is active or not
                  default: true
                scope:
                  type: string
                  description: Specify where the additional custom fields will apply
                  enum:
                  - REWARD
                  - ISSUE_REWARD
                  - CATALOGUE_PROMOTION
                dataType:
                  type: string
                  description: Type of data for the custom field. 255 is the character limit with datatype
                    as string
                  enum:
                  - BOOLEAN
                  - ENUM
                  - DATE
                  - STRING
                  - INTEGER
                enumValues:
                  type: array
                  description: Object containing the enum values. This parameter is required if dataType
                    is ENUM.
                  items:
                    type: string
            examples:
              request body:
                value:
                  orgId: 100458
                  name: CF1A112
                  description: CF1A112
                  isMandatory: false
                  isActive: true
                  scope: REWARD
                  defaultValue: null
                  dataType: STRING
              'scope : Catalogue Promotion':
                value:
                  orgId: 100458
                  name: Order confirmed
                  description: Reward is processing
                  isMandatory: false
                  isActive: true
                  scope: CATALOGUE_PROMOTION
                  defaultValue: null
                  dataType: STRING
              'scope: Issue Reward':
                value:
                  orgId: 100458
                  name: Order confirmed
                  description: Reward is processing
                  isMandatory: false
                  isActive: true
                  scope: CATALOGUE_PROMOTION
                  defaultValue: null
                  dataType: STRING
      responses:
        '200':
          description: '200'
          content:
            application/json:
              examples:
                'Scope: REWARD':
                  value:
                    id: 18833
                    orgId: 100737
                    name: CustomField1
                    description: CustomField1
                    isMandatory: false
                    isActive: true
                    scope: REWARD
                    defaultValue: null
                    dataType: STRING
                    createdBy: 75152721
                    createdOn: 1741934782959
                    createdOnDateTime: '2025-03-14T06:46:22Z'
                    lastUpdatedBy: 75152721
                    lastUpdatedOn: 1741934782959
                    enumValues: null
                    lastUpdatedOnDateTime: '2025-03-14T06:46:22Z'
                'Scope: CATALOGUE_PROMOTION':
                  value:
                    id: 6913
                    orgId: 100458
                    name: Order confirmed
                    description: Reward is processing
                    isMandatory: false
                    isActive: true
                    scope: CATALOGUE_PROMOTION
                    defaultValue: null
                    dataType: STRING
                    createdBy: 75130850
                    createdOn: null
                    lastUpdatedBy: 75130850
                    lastUpdatedOn: null
                'Scope: ISSUE_REWARD':
                  value:
                    id: 210
                    orgId: 100458
                    name: CF1A112
                    description: CF1A112
                    isMandatory: false
                    isActive: true
                    scope: ISSUE_REWARD
                    defaultValue: null
                    dataType: STRING
                    createdBy: 75086856
                    createdOn: null
                    lastUpdatedBy: 75086856
                    lastUpdatedOn: null
                'dataType: ENUM':
                  value:
                    orgId: 100458
                    name: CustomField
                    description: ''
                    isMandatory: false
                    isActive: false
                    defaultValue: PRIMARY
                    dataType: ENUM
                    scope: ISSUE_REWARD
                    enumValues:
                    - PRIMARY
                    - SECONDARY
                Sample response:
                  summary: Sample response
                  value:
                    id: 32546
                    orgId: 100737
                    name: terrorz
                    description: Custom Field of STRING Type
                    isMandatory: false
                    isActive: true
                    scope: CATALOGUE_PROMOTION
                    defaultValue: null
                    dataType: STRING
                    createdBy: 75197372
                    createdOn: null
                    createdOnDateTime: null
                    lastUpdatedBy: 75197372
                    lastUpdatedOn: null
                    enumValues: null
                    lastUpdatedOnDateTime: null
              schema:
                oneOf:
                - title: 'Scope: REWARD'
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 18833
                      default: 0
                    orgId:
                      type: integer
                      example: 100737
                      default: 0
                    name:
                      type: string
                      example: CustomField1
                    description:
                      type: string
                      example: CustomField1
                    isMandatory:
                      type: boolean
                      example: false
                      default: true
                    isActive:
                      type: boolean
                      example: true
                      default: true
                    scope:
                      type: string
                      example: REWARD
                    defaultValue: {}
                    dataType:
                      type: string
                      example: STRING
                    createdBy:
                      type: integer
                      example: 75152721
                      default: 0
                    createdOn:
                      type: integer
                      example: 1741934782959
                      default: 0
                    createdOnDateTime:
                      type: string
                      example: '2025-03-14T06:46:22Z'
                    lastUpdatedBy:
                      type: integer
                      example: 75152721
                      default: 0
                    lastUpdatedOn:
                      type: integer
                      example: 1741934782959
                      default: 0
                    enumValues: {}
                    lastUpdatedOnDateTime:
                      type: string
                      example: '2025-03-14T06:46:22Z'
                - title: 'Scope: CATALOGUE_PROMOTION'
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 6913
                      default: 0
                    orgId:
                      type: integer
                      example: 100458
                      default: 0
                    name:
                      type: string
                      example: Order confirmed
                    description:
                      type: string
                      example: Reward is processing
                    isMandatory:
                      type: boolean
                      example: false
                      default: true
                    isActive:
                      type: boolean
                      example: true
                      default: true
                    scope:
                      type: string
                      example: CATALOGUE_PROMOTION
                    defaultValue: {}
                    dataType:
                      type: string
                      example: STRING
                    createdBy:
                      type: integer
                      example: 75130850
                      default: 0
                    createdOn: {}
                    lastUpdatedBy:
                      type: integer
                      example: 75130850
                      default: 0
                    lastUpdatedOn: {}
                - title: 'Scope: ISSUE_REWARD'
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 210
                      default: 0
                    orgId:
                      type: integer
                      example: 100458
                      default: 0
                    name:
                      type: string
                      example: CF1A112
                    description:
                      type: string
                      example: CF1A112
                    isMandatory:
                      type: boolean
                      example: false
                      default: true
                    isActive:
                      type: boolean
                      example: true
                      default: true
                    scope:
                      type: string
                      example: ISSUE_REWARD
                    defaultValue: {}
                    dataType:
                      type: string
                      example: STRING
                    createdBy:
                      type: integer
                      example: 75086856
                      default: 0
                    createdOn: {}
                    lastUpdatedBy:
                      type: integer
                      example: 75086856
                      default: 0
                    lastUpdatedOn: {}
                - title: 'dataType: ENUM'
                  type: object
                  properties:
                    orgId:
                      type: integer
                      example: 100458
                      default: 0
                    name:
                      type: string
                      example: CustomField
                    description:
                      type: string
                      example: ''
                    isMandatory:
                      type: boolean
                      example: false
                      default: true
                    isActive:
                      type: boolean
                      example: false
                      default: true
                    defaultValue:
                      type: string
                      example: PRIMARY
                    dataType:
                      type: string
                      example: ENUM
                    scope:
                      type: string
                      example: ISSUE_REWARD
                    enumValues:
                      type: array
                      items:
                        type: string
                        example: PRIMARY
        '400':
          description: '400'
          content:
            application/json:
              examples:
                Wrong default value:
                  value:
                    status:
                      success: false
                      code: 3025
                      message: Default value not found in the enum list
                ENUM value empty:
                  value:
                    status:
                      success: false
                      code: 3030
                      message: Enum value cannot be empty
                Unsupported character in ENUM:
                  value:
                    status:
                      success: false
                      code: 3024
                      message: 'Invalid characters in enum value. Allowed characters: [a-z,A-Z,0-9,[]()-_
                        ]'
                No ENUM provided:
                  value:
                    status:
                      success: false
                      code: 400
                      message: ENUM's list size is out of limit
                ENUM character limit exceeded:
                  value:
                    status:
                      success: false
                      code: 3028
                      message: Enum value exceeds the limit of 80 characters
                Duplicate ENUM values provided:
                  value:
                    status:
                      success: false
                      code: 3029
                      message: Duplicate enum values found
              schema:
                oneOf:
                - title: Wrong default value
                  type: object
                  properties:
                    status:
                      type: object
                      properties:
                        success:
                          type: boolean
                          example: false
                          default: true
                        code:
                          type: integer
                          example: 3025
                          default: 0
                        message:
                          type: string
                          example: Default value not found in the enum list
                - title: ENUM value empty
                  type: object
                  properties:
                    status:
                      type: object
                      properties:
                        success:
                          type: boolean
                          example: false
                          default: true
                        code:
                          type: integer
                          example: 3030
                          default: 0
                        message:
                          type: string
                          example: Enum value cannot be empty
                - title: Unsupported character in ENUM
                  type: object
                  properties:
                    status:
                      type: object
                      properties:
                        success:
                          type: boolean
                          example: false
                          default: true
                        code:
                          type: integer
                          example: 3024
                          default: 0
                        message:
                          type: string
                          example: 'Invalid characters in enum value. Allowed characters: [a-z,A-Z,0-9,[]()-_
                            ]'
                - title: No ENUM provided
                  type: object
                  properties:
                    status:
                      type: object
                      properties:
                        success:
                          type: boolean
                          example: false
                          default: true
                        code:
                          type: integer
                          example: 400
                          default: 0
                        message:
                          type: string
                          example: ENUM's list size is out of limit
                - title: ENUM character limit exceeded
                  type: object
                  properties:
                    status:
                      type: object
                      properties:
                        success:
                          type: boolean
                          example: false
                          default: true
                        code:
                          type: integer
                          example: 3028
                          default: 0
                        message:
                          type: string
                          example: Enum value exceeds the limit of 80 characters
                - title: Duplicate ENUM values provided
                  type: object
                  properties:
                    status:
                      type: object
                      properties:
                        success:
                          type: boolean
                          example: false
                          default: true
                        code:
                          type: integer
                          example: 3029
                          default: 0
                        message:
                          type: string
                          example: Duplicate enum values found
      deprecated: false
      x-readme:
        code-samples:
        - code: |-
            curl --location 'https://eu.api.capillarytech.com/api_gateway/rewards/core/v1/brand/customfield' \
            --header 'Accept: application/json' \
            --header 'Content-Type: application/json' \
            --header 'accept: application/json' \
            --header 'Authorization: Basic bWFkaHVfcjU2YQ==' \
            --header 'Cookie: _cfuvid=EZk.XAGmnGytGPQFxLHCnFm_v4YhnMy7zloRQ46HJuo-1763640364440-0.0.1.1-604800000' \
            --data '{
                 Mandatory Parameters
                "name": "terrorz",
                "description": "Custom Field of STRING Type",
                "scope": "CATALOGUE_PROMOTION",
                "dataType": "STRING",
                 Non-Mandatory Parameters
                "orgId": 100737,
                "isMandatory": false,
                "isActive": true,
                 "defaultValue": "EV3",
                 "enumValues": ["EV1", "EV2", "EV3", "EV4", "EV5", "EV6", "EV7", "EV8", "EV9", "EV10", "EV11", "EV12", "EV13", "EV14", "EV15", "EV16", "EV17", "EV18", "EV19", "EV20", "EV21", "EV22", "EV23", "EV24", "EV25", "EV26", "EV27", "EV28", "EV29", "EV30"]
            }
          language: shell
          name: Sample request
        samples-languages:
        - shell
components:
  securitySchemes:
    sec0:
      type: http
      scheme: basic
