openapi: 3.1.0
info:
  title: Update Reward
  version: '1.0'
servers:
- url: https://{host}
  variables:
    host:
      default: host
security:
- sec0: []
paths:
  /api_gateway/rewards/core/v1/reward/{rewardId}/brand/{brandId}:
    put:
      summary: Update Reward
      description: ''
      operationId: put-update-reward
      parameters:
      - name: rewardId
        in: path
        description: Unique identifier of the reward.
        schema:
          type: string
        required: true
      - name: brandId
        in: path
        description: Unique identifier of the brand.
        schema:
          type: integer
          format: int64
        required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                RAW_BODY:
                  type: string
                  description: Request body
                  default: '{     "name": "testreward1poi",     "description": "testreward1",     "startTime":
                    "2025-09-26T20:00:00",     "endTime": "2026-10-31T11:59:30",     "priority": 1,     "type":
                    "VOUCHER",     "brandId": "1",     "enabled": true,     "intouchPoints": 500,     "geography":
                    [         {             "countryId": 1         }     ],     "categories": [         4     ],     "rewardRank":"1",     "intouchSeriesId":
                    "301233",     "redemptionType": "INTOUCH_REWARD",     "vendorRedemption": null,     "communications":
                    [         "1"     ],     "restrictions": {         "customerLevel": [             {                 "kpi":
                    "QUANTITY",                 "limit": 10,                 "repeatFrequencyType": "DAYS",                 "interval":
                    "30"             },             {                 "kpi": "QUANTITY",                 "limit":
                    50,                 "repeatFrequencyType": "MONTHS",                 "interval": "12"             }         ],         "rewardLevel":
                    [             {                 "kpi": "QUANTITY",                 "limit": 10000,                 "repeatFrequencyType":
                    "NO_LIMIT"             }         ]     },     "supplementaryCriteriaRO": [         {             "loyaltyProgramId":
                    469,             "tierIds": null,             "partnerProgramIds": [                 48             ]         },         {             "loyaltyProgramId":
                    690,             "tierIds": null,             "partnerProgramIds": null         }     ],     "customFields":
                    {         "CF1": "Custom field 1"     },     "languageSpecificInfo": [         {             "languageCode":
                    "en",             "name": "testreward1",             "description": "testreward1",             "imageId":
                    "bef4d522-2cf8-4fea-8087-376c449d5c85",             "termNConditions": "t&c",             "thumbnailId":
                    "c886f064-2b3f-4c19-9e86-7f7e5ab5ae04",             "termNConditionsId": "820a3d7f-2601-405b-9f56-4a3ba8e9df73",             "enabled":
                    true         }     ],     "isactive" : true }'
                  format: json
      responses:
        '200':
          description: '200'
          content:
            application/json:
              examples:
                Result:
                  value:
                    status:
                      success: true
                      code: 6006
                      message: Reward updated successfully
                    reward:
                      id: 458081
              schema:
                type: object
                properties:
                  status:
                    type: object
                    properties:
                      success:
                        type: boolean
                        example: true
                        default: true
                      code:
                        type: integer
                        example: 6006
                        default: 0
                      message:
                        type: string
                        example: Reward updated successfully
                  reward:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 112295
                        default: 0
        '400':
          description: '400'
          content:
            application/json:
              examples:
                '3014':
                  value:
                    status:
                      success: false
                      code: 3014
                      message: 'Unable to update reward as Org doesn''t have the custom field/s: labels,tag'
                    reward: null
                Result:
                  value:
                    status:
                      success: false
                      code: 400
                      message: Multiple payments is not supported within FREE and CONV_RATIO modes,Conversion
                        ratio can be set only for MILES, CASH_WALLET and CHARITY content types
                bad request 1:
                  value:
                    status:
                      success: false
                      code: 400
                      message: Passed entityId is not exists
              schema:
                oneOf:
                - title: '3014'
                  type: object
                  properties:
                    status:
                      type: object
                      properties:
                        success:
                          type: boolean
                          example: false
                          default: true
                        code:
                          type: integer
                          example: 3014
                          default: 0
                        message:
                          type: string
                          example: 'Unable to update reward as Org doesn''t have the custom field/s: labels,tag'
                    reward: {}
                - type: object
                  properties:
                    status:
                      type: object
                      properties:
                        success:
                          type: boolean
                          example: false
                          default: true
                        code:
                          type: integer
                          example: 400
                          default: 0
                        message:
                          type: string
                          example: Passed loyalty programId is not exists
                - title: bad request 1
                  type: object
                  properties:
                    status:
                      type: object
                      properties:
                        success:
                          type: boolean
                          example: false
                          default: true
                        code:
                          type: integer
                          example: 400
                          default: 0
                        message:
                          type: string
                          example: Passed entityId is not exists
                - type: object
                  properties:
                    status:
                      type: object
                      properties:
                        success:
                          type: boolean
                          example: false
                          default: true
                        code:
                          type: integer
                          example: 400
                          default: 0
                        message:
                          type: string
                          example: Multiple payments is not supported within FREE and CONV_RATIO modes,Conversion
                            ratio can be set only for MILES, CASH_WALLET and CHARITY content types
      deprecated: false
      x-readme:
        code-samples:
        - language: curl
          code: |-
            curl -L -X PUT 'https://eu.api.capillarytech.com/api_gateway/rewards/core/v1/reward/458081/brand/61' \
            -H 'Content-Type: application/json' \
            -H 'Authorization: Basic GM5ZmM2YjZlY2I2MmEy' \
            -H 'Cookie: _cfuvid=PZ2Qs9Lv6_ngy2fSsa2ZHebqE7qq7WrhJNpax_n8cXA-1759145375283-0.0.1.1-604800000' \
            -d '{
                "startTime": "2025-08-31T06:00:00Z",
                "endTime": "2025-09-30T11:59:30Z",
                "type": "VOUCHER",
                "brandId": "61",
                "redemptionType": "INTOUCH_REWARD",
                "priority": 1,
                "enabled": true,
                "intouchSeriesId": "849480",
                "intouchPoints": 500,
                "geography": [
                    {
                        "countryId": 1
                    }
                ],
                "categories": [
                    486
                ],
                "languageSpecificInfo": [
                    {
                        "languageCode": "en",
                        "name": "UAT Reward 10",
                        "description": "Test Reward for UAT Team",
                        "enabled": true,
                        "richContentRO": {
                            "UAT_RCT_1": {
                                "content": "Rich Content Text for UAT",
                                "isEnabled": true
                            }
                        }
                    }
                ],
                "paymentConfigs": [
                   {
                        "paymentMode": "POINTS",
                        "conversionRatio":0.33,
                        "points": 100
                    }
                ],
                "rewardRank":"1",
                "intouchSeriesId": "301233",
                "vendorRedemption": null,
                "communications": [
                    "1"
                ],
                "restrictions": {
                    "customerLevel": [
                        {
                            "kpi": "QUANTITY",
                            "limit": 10,
                            "repeatFrequencyType": "DAYS",
                            "interval": "30"
                        },
                        {
                            "kpi": "QUANTITY",
                            "limit": 50,
                            "repeatFrequencyType": "MONTHS",
                            "interval": "12"
                        }
                    ],
                    "rewardLevel": [
                        {
                            "kpi": "QUANTITY",
                            "limit": 10000,
                            "repeatFrequencyType": "NO_LIMIT"
                        }
                    ]
                },
                "supplementaryCriteriaRO": [
                    {
                        "loyaltyProgramId": 469,
                        "tierIds": null,
                        "partnerProgramIds": [
                            48
                        ]
                    },
                    {
                        "loyaltyProgramId": 690,
                        "tierIds": null,
                        "partnerProgramIds": null
                    }
                ],
                "customFields": {
                    "CF1": "Custom field 1"
                },
                "languageSpecificInfo": [
                    {
                        "languageCode": "en",
                        "name": "testreward1",
                        "description": "testreward1",
                        "imageId": "bef4d522-2cf8-4fea-8087-376c449d5c85",
                        "termNConditions": "t&c",
                        "thumbnailId": "c886f064-2b3f-4c19-9e86-7f7e5ab5ae04",
                        "termNConditionsId": "820a3d7f-2601-405b-9f56-4a3ba8e9df73",
                        "enabled": true
                    }
                ],
                "isactive" : true
            }'
          name: Sample cURL
        - language: curl
          code: "curl --location --request PUT 'https://eu.api.capillarytech.com/api_gateway/rewards/core/v1/reward/{rewardId}/brand/{brandId}'\
            \ \\\n--header 'Accept: application/json' \\\n--header 'Content-Type: application/json'\\\n\
            --header 'Authorization: Basic {token}' \\\n--data '{\n  \t\"name\":\"ABCD\",\n  \t\"description\"\
            :\"Reward\",\n    \"startTime\": \"2025-02-06T07:43:30.00Z\",\n    \"endTime\": \"2026-11-29T05:39:49.00Z\"\
            ,\n    \"type\": \"POINTS\",\n    \"brandId\": 3,\n    \"priority\": 1,\n    \"enabled\":\
            \ true,\n    \"intouchPoints\": 1,\n    \"intouchSeriesId\": \"6538e3ac60ce5c504144bb07\"\
            ,\n    \"tier\": \"SILVER\",\n    \"geography\": [\n        {\n            \"countryId\":\
            \ 7\n        }\n    ],\n    \"languageSpecificInfo\": [\n        {\n            \"languageCode\"\
            : \"en\",\n            \"name\": \" INTOUCH Enabled\",\n            \"description\": \"Description\"\
            ,\n            \"termNConditionsId\": \"EXDR12987R\",\n            \"imageId\": \"EXDR12987U\"\
            ,\n            \"thumbnailId\": \"EXDR12987T\",\n            \"enabled\": true,\n        \
            \    \"images\": [\n                {\n                    \"name\": \"imagename1\",\n   \
            \                 \"id\": \"9b648b66-5700-4c6d-84ea-01ddf73927c6\"\n                },\n \
            \               {\n                    \"name\": \"imagename2\",\n                    \"id\"\
            : \"9b648b66-5700-4c6d-84ea-01ddf73927c6\"\n                },\n                {\n      \
            \              \"name\": \"imagename2\",\n                    \"id\": \"9b648b66-5700-4c6d-84ea-01ddf73927c6\"\
            \n                }\n            ],\n            \"videos\": [\n                {\n      \
            \              \"name\": \"videoname1\",\n                    \"id\": \"9b648b66-5700-4c6d-84ea-01ddf73927c6\"\
            ,\n                    \"isExternal\": false\n                },\n                {\n    \
            \                \"name\": \"videoname1\",\n                    \"isExternal\": true\n   \
            \             }\n            ]\n        }\n    ],\n    \"categories\": [\n        5\n    ],\n\
            \    \"redemptionType\": \"CART_PROMOTION\",\n    \"communications\": [\n        4\n    ],\n\
            \    \"owners\": [\n        {\n            \"ownerType\": \"LOYALTY_PROGRAM\",\n         \
            \   \"ownerId\": \"123\"\n        }\n    ]\n}'"
          name: With image support
        - language: curl
          code: "curl --location --request PUT 'https://eu.api.capillarytech.com/api_gateway/rewards/core/v1/reward/{rewardId}/brand/{brandId}'\
            \ \\\n--header 'Accept: application/json' \\\n--header 'Content-Type: application/json'\\\n\
            --header 'Authorization: Basic {token}' \\\n--data '{\n    \"startTime\": \"2024-03-07T08:53:49.00Z\"\
            ,\n    \"endTime\": \"2024-03-14T05:39:49.00Z\",\n    \"type\": \"POINTS\",\n    \"brandId\"\
            : \"8\",\n    \"priority\": 1,\n    \"enabled\": true,\n    \"intouchPoints\": 3,\n    \"\
            intouchSeriesId\": \"73684275\",\n    \"tier\": \"GOLD\",\n    \"geography\":\n    [\n   \
            \     {\n            \"countryId\": \"14\"\n        }\n    ],\n    \"languageSpecificInfo\"\
            :\n    [\n        {\n            \"name\": \" INTOUCH Enabledsd\",\n            \"description\"\
            : \"Description\",\n            \"termNConditions\": \"https://s3.amazonaws.com/crm-nightly-new-solutions/IRISV2BRAND/EXDR12987R?X-Amz-Security-Token=FwoGZXIvYXdzEAgaDImRT4Rv3I22aidrESLdAQJokVqNlcxpwvh%2FuileYhmM7vAPvlqLv4pA3icQ0z4opwko8bn2w1y2412RtCR1AXAhlB82T%2FT%2Fr4lMjSRbBy1i4lsWgIVWWQ00NMLW2TDumQcnFwQq1p%2BQFAofb1GS%2BcE4zoWTMieFVV3%2F15l2stJ7ZmwnyDYkDyqGzCk0AWoeQQw%2F%2BHu6DbeIcBJrEakvjZvLjqzeIACunRAYgrXAMlI5HfPenJl8CmEfvhgluUkUNQ25vrL6KhXEQKG4rdVjWG%2BxnkMgcZqBLth64qvfYES1wVyYz1OvneIhOdKbKO3tpZoGMi0%2F3wHyU2g0g7XXMM1cLRtUIn6x6%2BEzEdHMArLUdsCYy%2BnDOfaViZiRnhOtV6U%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20221014T145408Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3600&X-Amz-Credential=ASIAXCQYYRKNMI6TM5YP%2F20221014%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=c17682bb64da475b6163148797a0c21dbb75fde352c2947fd94504d7f88535fe\"\
            ,\n            \"thumbnailId\": \"EXDR12987T\",\n            \"imageId\": \"EXDR12987U\",\n\
            \            \"enabled\": true,\n            \"termNConditionsId\": \"EXDR12987R\",\n    \
            \        \"languageCode\": \"en\",\n             \"customFields\":{\n               \"mandatory\
            \ - CF1\": \"englishvalue1\"\n               \n            }\n        },\n        {\n    \
            \        \"name\": \" INTOUCH Enabledsd\",\n            \"description\": \"Description\",\n\
            \            \"termNConditions\": \"https://s3.amazonaws.com/crm-nightly-new-solutions/IRISV2BRAND/EXDR12987R?X-Amz-Security-Token=FwoGZXIvYXdzEAgaDImRT4Rv3I22aidrESLdAQJokVqNlcxpwvh%2FuileYhmM7vAPvlqLv4pA3icQ0z4opwko8bn2w1y2412RtCR1AXAhlB82T%2FT%2Fr4lMjSRbBy1i4lsWgIVWWQ00NMLW2TDumQcnFwQq1p%2BQFAofb1GS%2BcE4zoWTMieFVV3%2F15l2stJ7ZmwnyDYkDyqGzCk0AWoeQQw%2F%2BHu6DbeIcBJrEakvjZvLjqzeIACunRAYgrXAMlI5HfPenJl8CmEfvhgluUkUNQ25vrL6KhXEQKG4rdVjWG%2BxnkMgcZqBLth64qvfYES1wVyYz1OvneIhOdKbKO3tpZoGMi0%2F3wHyU2g0g7XXMM1cLRtUIn6x6%2BEzEdHMArLUdsCYy%2BnDOfaViZiRnhOtV6U%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20221014T145408Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3600&X-Amz-Credential=ASIAXCQYYRKNMI6TM5YP%2F20221014%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=c17682bb64da475b6163148797a0c21dbb75fde352c2947fd94504d7f88535fe\"\
            ,\n            \"thumbnailId\": \"EXDR12987T\",\n            \"imageId\": \"EXDR12987U\",\n\
            \            \"enabled\": true,\n            \"termNConditionsId\": \"EXDR12987R\",\n    \
            \        \"languageCode\": \"fr\",\n            \"customFields\":{\n               \"non_mandatory-CF4\"\
            :\"frenchvalue4\"\n            }\n        }\n    ],\n    \"categories\":\n    [\n        \"\
            11\"\n    ],\n    \"redemptionType\": \"INTOUCH_REWARD\",\n    \"communications\":\n    [\n\
            \        \"11\"\n    ],\n    \"vendorRedemption\": null,\n    \"group\": null,\n    \"label\"\
            : null\n}'"
          name: With multi lingual custom field
        - language: curl
          code: |-
            curl --location --request PUT 'https://eu.api.capillarytech.com/api_gateway/rewards/core/v1/reward/{rewardId}/brand/{brandId}' \
            --header 'Accept: application/json' \
            --header 'Content-Type: application/json'\
            --header 'Authorization: Basic {token}' \
            --data '{
                "startTime": "2024-10-07T17:04:30.00Z",
                "endTime": "2027-10-31T05:39:49.00Z",
                "rewardRevenueMeta" : [
                    {
                        "commissionParticipant": "BRAND",
                        "commissionRate": "1.5",
                        "cycleStartDate": "2024-11-07T17:04:30.000Z",
                        "cycleEndDate": "2025-10-06T07:43:30.000Z"
                    },
                    {
                        "commissionParticipant": "AFFILIATE",
                        "commissionRate": "1.2",
                        "cycleStartDate": "2024-11-07T17:04:30.000Z",
                        "cycleEndDate": "2026-10-06T07:43:30.000Z"
                    }
                ],
                "rewardRevenueDefaults": [
                    {
                        "commissionParticipant": "AFFILIATE",
                        "defaultValue": "1.1"
                    },
                    {
                        "commissionParticipant": "END_CUSTOMER",
                        "defaultValue": "1.3"
                    }
                ],
                  "type": "VOUCHER",
              "brandId": 3,
              "priority": 1,
              "enabled": true,
              "intouchPoints": 1,
              "intouchSeriesId": "1135336",
              "tier": "SILVER",
              "geography": [
                {
                  "countryId": 7
                }
              ],
              "languageSpecificInfo": [
                {
                  "languageCode": "en",
                  "name": " INTOUCH Enabled",
                  "description": "Description",
                  "termNConditionsId": "EXDR12987R",
                  "imageId": "EXDR12987U",
                  "thumbnailId": "EXDR12987T",
                  "enabled": true
                }
              ],
              "categories": [
                5
              ],
              "redemptionType": "INTOUCH_REWARD",
              "communications": [
                4
              ],
              "owners":[{
                  "ownerType":"LOYALTY_PROGRAM",
                  "ownerId":"123"
                  }
              ]
            }'
          name: With revenue metadata
        - language: curl
          code: "curl --location --request PUT 'https://eu.api.capillarytech.com/api_gateway/rewards/core/v1/reward/367568/brand/61'\
            \ \\\n--header 'Content-Type: application/json' \\\n--header 'Authorization: Basic Z2VvcmdlLmpvaG5zb246OTg4OTU2NWI4ODVhMmY4ZWE1MTk1MjA2NWEwYTEzNzg='\
            \ \\\n--header 'Cookie: _cfuvid=qYQuCnm5.jAQe_tPrTV3.owL5NayLpGKA6eWAxMixcQ-1747723697739-0.0.1.1-604800000'\
            \ \\\n--data '{\n  \"name\": \"gold\",\n  \"description\": \"testreward1\",\n  \"startTime\"\
            : \"2025-01-26T20:00:00Z\",\n  \"endTime\": \"2026-10-31T11:59:30Z\",\n  \"type\": \"VOUCHER\"\
            ,\n  \"brandId\": 61,  \n  \"enabled\": true,\n  \"intouchPoints\": 500,\n  \"categories\"\
            : [229],\n  \"redemptionType\": \"VOUCHER\",  \n  \"paymentConfigs\": [\n    {\n      \"paymentMode\"\
            : \"POINTS\",\n      \"points\": 300  \n    }\n  ]\n}'"
          name: With paymentConfigs
        samples-languages:
        - curl
components:
  securitySchemes:
    sec0:
      type: http
      scheme: basic
