openapi: 3.1.0
info:
  title: Revoke enrolled badges
  version: '1.0'
servers:
- url: https://{host}
  variables:
    host:
      default: host
security:
- sec0: []
paths:
  /api_gateway/v1/badges/badgeMeta/customer/revokeIssue:
    post:
      summary: Revoke enrolled badges
      description: ''
      operationId: revoke-enrolment-of-a-badge
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - badgeMetaId
              - customers
              properties:
                badgeMetaId:
                  type: string
                  description: Unique identifier for the badge metadata
                customers:
                  type: object
                  properties:
                    customerID:
                      type: string
            examples:
              With Revoke Issuals:
                value:
                  badgeMetaId: 670371e39235f02fd5d71cbd
                  revokeIssuals:
                  - customerId: '387403362'
                    issueId: '236'
                  - customerId: '387403360'
                    issueId: '234'
              Multiple customers:
                value:
                  badgeMetaId: 654bb48766a87827bb61e631
                  customers:
                  - 123
                  - 62090013
      responses:
        '200':
          description: '200'
          content:
            application/json:
              examples:
                Single Customer:
                  value:
                    data:
                      badgeMetaId: 653de84db3cda7078c7c68ed
                      revokedIssuedBadges:
                      - customerId: 62090013
                        issuedId: 653e024bb3cda7078c7c6903
                        error: null
                      requestId: null
                    errors: []
                    warnings: []
                'Failure: Customer is not issued':
                  value:
                    data:
                      badgeMetaId: 653de84db3cda7078c7c68ed
                      revokedIssuedBadges:
                      - customerId: 123
                        issuedId: null
                        error:
                          code: 404
                          message: Customer doesn't have issue instance
                          reference: null
                      requestId: null
                    errors: []
                    warnings: []
                Multiple Customer:
                  value:
                    data:
                      badgeMetaId: 654bb48766a87827bb61e631
                      revokedIssuedBadges:
                      - customerId: 123
                        issuedId: 654cc02b6bccde1274b6d3a7
                        error: null
                      - customerId: 62090013
                        issuedId: 654cc03e6bccde1274b6d3a9
                        error: null
                      requestId: null
                    errors: []
                    warnings: []
                With Revoke Issual:
                  value:
                    data:
                      badgeMetaId: 66e3ef1b5abea9582ae4f301
                      revokedIssuedBadges:
                      - customerId: 12323
                        issuedId: 66e3ef1e5abea9582ae4f302
                    errors: []
                    warnings: []
                'Failure: RevokeIssuals or CustomerId is not passed':
                  value:
                    data: null
                    errors:
                    - code: 1051
                      message: RevokeIssuals or CustomerId is mandatory
                      reference: null
                    warnings: null
              schema:
                oneOf:
                - title: Single Customer
                  type: object
                  properties:
                    data:
                      type: object
                      properties:
                        badgeMetaId:
                          type: string
                          example: 653de84db3cda7078c7c68ed
                        revokedIssuedBadges:
                          type: array
                          items:
                            type: object
                            properties:
                              customerId:
                                type: integer
                                example: 62090013
                                default: 0
                              issuedId:
                                type: string
                                example: 653e024bb3cda7078c7c6903
                              error: {}
                        requestId: {}
                    errors:
                      type: array
                    warnings:
                      type: array
                - title: 'Failure: Customer is not issued'
                  type: object
                  properties:
                    data:
                      type: object
                      properties:
                        badgeMetaId:
                          type: string
                          example: 653de84db3cda7078c7c68ed
                        revokedIssuedBadges:
                          type: array
                          items:
                            type: object
                            properties:
                              customerId:
                                type: integer
                                example: 123
                                default: 0
                              issuedId: {}
                              error:
                                type: object
                                properties:
                                  code:
                                    type: integer
                                    example: 404
                                    default: 0
                                  message:
                                    type: string
                                    example: Customer doesn't have issue instance
                                  reference: {}
                        requestId: {}
                    errors:
                      type: array
                    warnings:
                      type: array
                - title: Multiple Customer
                  type: object
                  properties:
                    data:
                      type: object
                      properties:
                        badgeMetaId:
                          type: string
                          example: 654bb48766a87827bb61e631
                        revokedIssuedBadges:
                          type: array
                          items:
                            type: object
                            properties:
                              customerId:
                                type: integer
                                example: 123
                                default: 0
                              issuedId:
                                type: string
                                example: 654cc02b6bccde1274b6d3a7
                              error: {}
                        requestId: {}
                    errors:
                      type: array
                    warnings:
                      type: array
                - title: With Revoke Issual
                  type: object
                  properties:
                    data:
                      type: object
                      properties:
                        badgeMetaId:
                          type: string
                          example: 66e3ef1b5abea9582ae4f301
                        revokedIssuedBadges:
                          type: array
                          items:
                            type: object
                            properties:
                              customerId:
                                type: integer
                                example: 12323
                                default: 0
                              issuedId:
                                type: string
                                example: 66e3ef1e5abea9582ae4f302
                    errors:
                      type: array
                    warnings:
                      type: array
                - title: 'Failure: RevokeIssuals or CustomerId is not passed'
                  type: object
                  properties:
                    data: {}
                    errors:
                      type: array
                      items:
                        type: object
                        properties:
                          code:
                            type: integer
                            example: 1051
                            default: 0
                          message:
                            type: string
                            example: RevokeIssuals or CustomerId is mandatory
                          reference: {}
                    warnings: {}
        '404':
          description: '404'
          content:
            application/json:
              examples:
                Result:
                  value:
                    data: null
                    errors:
                    - code: 404
                      message: Passed badge is not found
                      reference: null
                    warnings: null
              schema:
                type: object
                properties:
                  data: {}
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        code:
                          type: integer
                          example: 404
                          default: 0
                        message:
                          type: string
                          example: Passed badge is not found
                        reference: {}
                  warnings: {}
      deprecated: false
components:
  securitySchemes:
    sec0:
      type: http
      scheme: basic
