openapi: 3.1.0
info:
  title: Update Reward Expiry Reminder
  version: '1.0'
servers:
- url: https://{host}
  variables:
    host:
      default: host
security:
- sec0: []
paths:
  /api_gateway/rewards/core/v1/reward/expiryReminder/{rewardExpiryReminderid}:
    put:
      summary: Update Reward Expiry Reminder
      description: ''
      operationId: update-reward-expiry-reminder
      parameters:
      - name: rewardExpiryReminderid
        in: path
        description: Unique identifier of Reward Expiry Reminder
        schema:
          type: integer
          format: int32
        required: true
      responses:
        '200':
          description: '200'
          content:
            application/json:
              examples:
                Result:
                  value:
                    status:
                      success: true
                      code: 12040
                      message: Reward expiry reminder updated
                    rewardExpiryReminder:
                      id: 34
                      orgId: 100737
                      duration: 15
                      durationType: DAYS
                      cronTaskId: 605157
                      timing: '12:00'
                      isActive: true
                      createdOn: 1741892481000
                      createdOnDateTime: '2025-03-13T19:01:21Z'
                      lastUpdatedOn: 1741892497000
                      lastUpdatedOnDateTime: '2025-03-13T19:01:37Z'
                      createdBy: 75155282
                      lastUpdatedBy: 75155282
              schema:
                type: object
                properties:
                  status:
                    type: object
                    properties:
                      success:
                        type: boolean
                        example: true
                        default: true
                      code:
                        type: integer
                        example: 12040
                        default: 0
                      message:
                        type: string
                        example: Reward expiry reminder updated
                  rewardExpiryReminder:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 34
                        default: 0
                      orgId:
                        type: integer
                        example: 100737
                        default: 0
                      duration:
                        type: integer
                        example: 15
                        default: 0
                      durationType:
                        type: string
                        example: DAYS
                      cronTaskId:
                        type: integer
                        example: 605157
                        default: 0
                      timing:
                        type: string
                        example: '12:00'
                      isActive:
                        type: boolean
                        example: true
                        default: true
                      createdOn:
                        type: integer
                        example: 1741892481000
                        default: 0
                      createdOnDateTime:
                        type: string
                        example: '2025-03-13T19:01:21Z'
                      lastUpdatedOn:
                        type: integer
                        example: 1741892497000
                        default: 0
                      lastUpdatedOnDateTime:
                        type: string
                        example: '2025-03-13T19:01:37Z'
                      createdBy:
                        type: integer
                        example: 75155282
                        default: 0
                      lastUpdatedBy:
                        type: integer
                        example: 75155282
                        default: 0
        '400':
          description: '400'
          content:
            application/json:
              examples:
                Duration is mandatory:
                  value:
                    status:
                      success: false
                      code: 400
                      message: Duration is mandatory
                Invalid Reward expiry reminder ID:
                  value:
                    status:
                      success: false
                      code: 400
                      message: Reward expiry reminder with id 34 does not exist
              schema:
                oneOf:
                - title: Duration is mandatory
                  type: object
                  properties:
                    status:
                      type: object
                      properties:
                        success:
                          type: boolean
                          example: false
                          default: true
                        code:
                          type: integer
                          example: 400
                          default: 0
                        message:
                          type: string
                          example: Duration is mandatory
                - title: Invalid Reward expiry reminder ID
                  type: object
                  properties:
                    status:
                      type: object
                      properties:
                        success:
                          type: boolean
                          example: false
                          default: true
                        code:
                          type: integer
                          example: 400
                          default: 0
                        message:
                          type: string
                          example: Reward expiry reminder with id 34 does not exist
      deprecated: false
      x-readme:
        code-samples:
        - language: curl
          code: |-
            curl --location --request PUT 'https://eu.api.capillarytech.com/api_gateway/rewards/core/v1/reward/expiryReminder/1' \
            --header 'Content-Type: application/json' \
            --header 'Authorization: Basic aWFtc2hpdBLAHBLAHI3YjJlODM4ZjhlMzRkNWI1YTI5MWY=' \
            --header 'user-agent: pyapps_auto_2024-05-25-12-47-39' \
            --header 'Cookie: _cfuvid=EdYU22mJWP1xzoxt74hggY7PKdhUOcIzYPQlaq4bOyU-1727677397251-0.0.1.1-604800000' \
            --data '{
                "isActive":true,
                "duration": 15,
                "timing": "12:00"
            }'
        samples-languages:
        - curl
components:
  securitySchemes:
    sec0:
      type: http
      scheme: basic
